# GENERATED by scripts/vendor_ripple_verbs.py. DO NOT EDIT BY HAND.
# Source: ripple packages/core/src/schema/event-handler.ts (EventAction)
# Commit: 66ff6f6948729917213c98bf4488f7bfc286da8f
# Re-run the script to refresh; tests/test_ripple_action_verbs_vendored.py checks
# VERBS_SHA256 always, and the source hash when a ripple checkout is beside us.
"""Ripple event action verbs, generated from ripple's schema."""

SOURCE_COMMIT = "66ff6f6948729917213c98bf4488f7bfc286da8f"
SOURCE_SHA256 = "009727f76f7ec76377885d938cd3b117a42fce4c0a50275f23816ff312a636c5"
VERBS_SHA256 = "68e8d2d335efaa9f5746bf9fe40d0548be5f9d50dd002d1d123f1284d6f55f68"

ACTION_VERBS: frozenset[str] = frozenset(
    {
        "set",
        "toggle",
        "push",
        "remove",
        "api",
        "run_source",
        "call_binding",
        "invoke_tool",
        "navigate",
        "toast",
        "emit",
        "open",
        "pin",
        "unpin",
        "flow",
        "branch",
        "confirm",
        "validate",
        "delay",
        "invoke",
        "animate",
    }
)
