# ee/pocketpaw_ee/sites/ai_ready.py — the files that make a published Paw Site
# readable by search engines and AI assistants: robots.txt, sitemap.xml, llms.txt,
# a markdown copy of every page, the ``_headers`` rules that advertise those copies,
# a LocalBusiness JSON-LD block, and the IndexNow key file. Plus the IndexNow ping.
#
# Created 2026-10-03 (feat/ai-ready-sites, AV-1). Why this exists: a site on
# ``*.workers.dev`` lives on Cloudflare's zone, not ours, so the zone features that
# would do this for us (managed robots.txt, Crawler Hints, Markdown for Agents)
# cannot be switched on. Before this, a live site served only Cloudflare's
# Content-Signals comment at /robots.txt and 404'd on /sitemap.xml and /llms.txt.
# AI crawlers do not run JavaScript, and blocking OAI-SearchBot removes a site from
# ChatGPT search answers, so the files have to ship inside the site itself.
#
# Everything here is PURE except ``ping_indexnow``: builders take strings and return
# strings/bytes, and ``workers_deploy`` does the disk writes. The one owner switch is
# ``ai_training_allowed``; it changes only the training lines in robots.txt (the
# Content-Signal ``ai-train`` value and the per-bot Disallow blocks). Search and
# assistant bots are never blocked either way.

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass
from html import unescape
from xml.sax.saxutils import escape as xml_escape

logger = logging.getLogger(__name__)

# Bots that collect TRAINING data. Blocked unless the owner opts in.
TRAINING_BOTS = ("GPTBot", "ClaudeBot", "Google-Extended", "Applebot-Extended", "CCBot")
# Bots that power search answers and live assistant fetches. NEVER blocked: OpenAI
# documents that blocking OAI-SearchBot drops a site from ChatGPT search.
SEARCH_BOTS = (
    "OAI-SearchBot",
    "ChatGPT-User",
    "Claude-SearchBot",
    "Claude-User",
    "PerplexityBot",
    "Perplexity-User",
)

INDEXNOW_ENDPOINT = "https://api.indexnow.org/indexnow"

# Marks the files WE generated, so a republish overwrites our own copy but never a
# file the site author shipped (an imported site can carry its own robots.txt).
MARKER = "generated by PocketPaw"
_HEADERS_START = "# === START POCKETPAW AI-READY ==="
_HEADERS_END = "# === END POCKETPAW AI-READY ==="
# Cloudflare caps ``_headers`` at 100 rules; the svelte adapter writes two of its own.
# ponytail: pages past this cap get no Link header (their .md copy still exists).
MAX_HEADER_RULES = 80
_LD_ATTR = "data-paw-ai-ready"

# Error pages and SvelteKit's SPA fallback are not content.
_SKIP_PAGES = {"404", "500", "200"}

_KEY_RE = re.compile(r"^[a-zA-Z0-9-]{8,128}$")


def enabled() -> bool:
    """``POCKETPAW_SITES_AI_READY`` — ON unless set to 0/false/off/no."""
    raw = os.environ.get("POCKETPAW_SITES_AI_READY", "").strip().lower()
    return raw not in {"0", "false", "off", "no"}


@dataclass(frozen=True)
class AiReadyInputs:
    """What the publish seam knows about a site that the deployer does not.

    ``host`` is the canonical public hostname (a live custom domain, or the site's
    workers.dev host). Empty lets ``deploy_workers`` derive the workers.dev host
    from the Worker name it is about to deploy under."""

    site_name: str
    description: str = ""
    ai_training_allowed: bool = False
    indexnow_key: str = ""
    host: str = ""


@dataclass(frozen=True)
class Page:
    """One built HTML page: its path relative to the asset dir, and its markup."""

    rel_path: str
    html: str


def page_route(rel_path: str) -> str | None:
    """The URL a page is served at under Workers' default ``auto-trailing-slash``
    handling, or None for a file that is not a content page.

    ``index.html`` → ``/``; ``about.html`` → ``/about``; ``docs/index.html`` →
    ``/docs/``."""
    parts = rel_path.split("/")
    if any(p.startswith(("_", ".")) or p == "node_modules" for p in parts):
        return None
    stem, dot, ext = rel_path.rpartition(".")
    if not dot or ext.lower() not in {"html", "htm"} or stem in _SKIP_PAGES:
        return None
    if stem == "index":
        return "/"
    if stem.endswith("/index"):
        return "/" + stem[: -len("index")]
    return "/" + stem


def markdown_path(route: str) -> str:
    """Where a route's markdown copy lives: ``/`` → ``/index.md``, ``/about`` →
    ``/about.md``, ``/docs/`` → ``/docs.md``."""
    stem = route.strip("/")
    return f"/{stem or 'index'}.md"


def _title(html: str, fallback: str) -> str:
    m = re.search(r"<title[^>]*>(.*?)</title>", html, re.I | re.S)
    text = " ".join(unescape(m.group(1)).split()) if m else ""
    return text or fallback


def html_to_markdown(html: str) -> str:
    """Rendered HTML → markdown. html2text when installed (the ``extract`` extra the
    cloud image ships with), else the plain visible text the KB ingest uses — plain
    text is still valid markdown, and a publish must not depend on an optional dep."""
    from pocketpaw_ee.sites import badge

    html = badge.strip_badge(html)
    try:
        import html2text
    except ImportError:
        from pocketpaw_ee.sites.kb_ingest import html_to_text

        return html_to_text(html).strip() + "\n"
    conv = html2text.HTML2Text()
    conv.body_width = 0
    conv.ignore_images = True
    return conv.handle(html).strip() + "\n"


def build_robots_txt(host: str, ai_training_allowed: bool) -> str:
    train = "yes" if ai_training_allowed else "no"
    lines = [
        f"# {MARKER}",
        "User-agent: *",
        f"Content-Signal: search=yes, ai-input=yes, ai-train={train}",
        "Allow: /",
        "",
    ]
    if not ai_training_allowed:
        for bot in TRAINING_BOTS:
            lines += [f"User-agent: {bot}", "Disallow: /", ""]
    lines.append(f"Sitemap: https://{host}/sitemap.xml")
    return "\n".join(lines) + "\n"


def build_sitemap_xml(host: str, routes: list[str], lastmod: str) -> str:
    urls = "".join(
        f"  <url><loc>{xml_escape(f'https://{host}{r}')}</loc><lastmod>{lastmod}</lastmod></url>\n"
        for r in routes
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- {MARKER} -->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{urls}</urlset>\n"
    )


def build_llms_txt(
    host: str, site_name: str, description: str, pages: list[tuple[str, str]]
) -> str:
    """``pages`` is ``[(route, title)]``. Format per llmstxt.org: H1 name, a
    blockquote summary, then an H2 section of links (to the markdown copies)."""
    out = [f"# {site_name or host}", ""]
    if description:
        out += [f"> {' '.join(description.split())}", ""]
    out += ["## Pages", ""]
    out += [f"- [{title}](https://{host}{markdown_path(route)})" for route, title in pages]
    out += ["", f"<!-- {MARKER} -->"]
    return "\n".join(out) + "\n"


def build_headers_block(routes: list[str]) -> str:
    """The ``_headers`` rules (Workers Static Assets syntax) that point each page at
    its markdown copy with an RFC 8288 ``Link`` header. Wrapped in sentinels so a
    republish replaces its own block and leaves the author's/adapter's rules alone."""
    lines = [_HEADERS_START]
    for route in routes[:MAX_HEADER_RULES]:
        lines += [route, f'  Link: <{markdown_path(route)}>; rel="alternate"; type="text/markdown"']
    lines.append(_HEADERS_END)
    return "\n".join(lines) + "\n"


def merge_headers(existing: str, block: str) -> str:
    """Drop any earlier AI-ready block from ``existing`` and append ``block``."""
    stripped = re.sub(
        re.escape(_HEADERS_START) + r".*?" + re.escape(_HEADERS_END) + r"\n?",
        "",
        existing,
        flags=re.S,
    )
    if stripped and not stripped.endswith("\n"):
        stripped += "\n"
    return stripped + block


def find_business(pages: list[Page]) -> dict[str, str]:
    """Contact details as the site itself publishes them: the first ``tel:`` link
    and the first ``<address>`` element. No structured business record exists on a
    Site, so the rendered page is the only source that cannot drift from what the
    visitor sees."""
    found: dict[str, str] = {}
    for page in pages:
        if "telephone" not in found:
            m = re.search(r"""href\s*=\s*["']tel:([^"']+)["']""", page.html, re.I)
            if m:
                found["telephone"] = unescape(m.group(1)).strip()
        if "address" not in found:
            m = re.search(r"<address[^>]*>(.*?)</address>", page.html, re.I | re.S)
            if m:
                text = " ".join(unescape(re.sub(r"<[^>]+>", " ", m.group(1))).split())
                if text:
                    found["address"] = text
    return found


def build_json_ld(host: str, site_name: str, description: str, business: dict[str, str]) -> str:
    """A ``<script type="application/ld+json">`` LocalBusiness block, or "" when the
    site publishes neither a phone number nor an address (a LocalBusiness with only
    a name says nothing a crawler did not already know)."""
    if not (business.get("telephone") or business.get("address")):
        return ""
    data: dict[str, object] = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": site_name or host,
        "url": f"https://{host}/",
    }
    if description:
        data["description"] = description
    if business.get("telephone"):
        data["telephone"] = business["telephone"]
    if business.get("address"):
        data["address"] = business["address"]
    if business.get("openingHours"):
        data["openingHours"] = business["openingHours"]
    # ensure_ascii + escaping "<" keeps "</script>" in any field from closing the tag.
    body = json.dumps(data, ensure_ascii=True).replace("<", "\\u003c")
    return f'<script type="application/ld+json" {_LD_ATTR}>{body}</script>'


_OUR_LD_RE = re.compile(r'<script type="application/ld\+json" ' + _LD_ATTR + r">.*?</script>", re.S)


def inject_json_ld(html: str, block: str) -> str | None:
    """The page with ``block`` in its head, or None when it should be left alone:
    no ``</head>``, or the author already ships their own JSON-LD."""
    page = _OUR_LD_RE.sub("", html)
    if not block or "application/ld+json" in page.lower():
        return page if page != html else None
    idx = page.lower().find("</head>")
    if idx < 0:
        return None
    return page[:idx] + block + page[idx:]


def build_ai_ready_files(
    host: str,
    pages: list[Page],
    inputs: AiReadyInputs,
    lastmod: str,
) -> dict[str, bytes]:
    """Every file to write into the asset dir, keyed by its path relative to it.

    Includes rewritten HTML pages when JSON-LD is injected, and the merged
    ``_headers`` is NOT here: it depends on the file already on disk, so the writer
    merges ``build_headers_block`` itself."""
    routed = [(page_route(p.rel_path), p) for p in pages]
    routed = sorted([(r, p) for r, p in routed if r is not None], key=lambda rp: rp[0])
    routes = [r for r, _ in routed]
    files: dict[str, bytes] = {
        "robots.txt": build_robots_txt(host, inputs.ai_training_allowed).encode(),
        "sitemap.xml": build_sitemap_xml(host, routes, lastmod).encode(),
        "llms.txt": build_llms_txt(
            host,
            inputs.site_name,
            inputs.description,
            [(r, _title(p.html, r)) for r, p in routed],
        ).encode(),
    }
    for route, page in routed:
        files[markdown_path(route).lstrip("/")] = html_to_markdown(page.html).encode()
    if _KEY_RE.match(inputs.indexnow_key or ""):
        files[f"{inputs.indexnow_key}.txt"] = inputs.indexnow_key.encode()
    ld = build_json_ld(
        host, inputs.site_name, inputs.description, find_business([p for _, p in routed])
    )
    for _, page in routed:
        new = inject_json_ld(page.html, ld)
        if new is not None and new != page.html:
            files[page.rel_path] = new.encode()
    return files


def page_urls(host: str, pages: list[Page]) -> list[str]:
    routes = sorted(r for r in (page_route(p.rel_path) for p in pages) if r is not None)
    return [f"https://{host}{r}" for r in routes]


async def ping_indexnow(host: str, key: str, urls: list[str]) -> bool:
    """Tell IndexNow (Bing, Yandex, Seznam, Naver; Google does not participate) that
    these URLs changed. Short timeout, never raises: a publish must not fail or
    stall because a search engine's endpoint is slow. Returns whether it was
    accepted (200/202)."""
    if not (host and _KEY_RE.match(key or "") and urls):
        return False
    payload = {
        "host": host,
        "key": key,
        "keyLocation": f"https://{host}/{key}.txt",
        "urlList": urls[:10_000],
    }
    try:
        import httpx

        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.post(INDEXNOW_ENDPOINT, json=payload)
        if resp.status_code in (200, 202):
            return True
        logger.warning("sites.ai_ready: IndexNow answered %s for %s", resp.status_code, host)
    except Exception:  # noqa: BLE001 — never fail a publish over a ping
        logger.warning("sites.ai_ready: IndexNow ping failed for %s", host, exc_info=True)
    return False


__all__ = [
    "AiReadyInputs",
    "Page",
    "build_ai_ready_files",
    "build_headers_block",
    "enabled",
    "merge_headers",
    "page_urls",
    "ping_indexnow",
]
