// ee/pocketpaw_ee/sites/edit_bridge.js --
// the paw-sites edit-bridge, injected into html drafts served with ?paw_edit=1.
//
// Generated by scripts/vendor-paw-sites-edit-bridge.sh from paw-sites 15414fe
// (src/edit-bridge.ts). Do not hand-edit. The quoted "__PAW_BUILDER_ORIGIN__"
// placeholder is replaced with the builder origin by preview_origin.py.

(function () {
  try {
    if (window.parent === window) return;
(function () {
  try {
    if (window.parent === window || window.__pawRuntimeReporter) return;
    window.__pawRuntimeReporter = true;
    var TARGET = "__PAW_BUILDER_ORIGIN__";
    var NONCE = new URLSearchParams(window.location.search).get("paw_nonce") || "";
    function emit(msg) {
      msg.__pawRuntime = true; msg.nonce = NONCE;
      try { window.parent.postMessage(msg, TARGET); } catch (_) {}
    }
    function report(m) {
      emit({ type: "error", message: String(m).slice(0, 300) });
    }
    window.addEventListener("error", function (e) { report((e && e.message) || "Script error"); });
    window.addEventListener("unhandledrejection", function (e) { var r = e && e.reason; report((r && r.message) || r || "Unhandled rejection"); });
    var lastPath = null;
    function reportLocation() {
      try {
        var l = window.location, q = new URLSearchParams(l.search);
        q.delete("paw_edit"); q.delete("paw_nonce");
        var qs = q.toString();
        var path = l.pathname + (qs ? "?" + qs : "") + l.hash;
        if (path === lastPath) return;
        lastPath = path;
        emit({ type: "location", path: path });
      } catch (_) {}
    }
    function wrapHistory(name) {
      try {
        var h = window.history, orig = h && h[name];
        if (typeof orig !== "function") return;
        h[name] = function () { var r = orig.apply(this, arguments); reportLocation(); return r; };
      } catch (_) {}
    }
    wrapHistory("pushState"); wrapHistory("replaceState");
    window.addEventListener("popstate", reportLocation);
    window.addEventListener("hashchange", reportLocation);
    reportLocation();
  } catch (_) { /* never break the page */ }
})();
    var params = new URLSearchParams(window.location.search);
    if (params.get("paw_edit") !== '1') return;
    var ORIGIN = "__PAW_BUILDER_ORIGIN__";
    var NONCE = params.get("paw_nonce") || "";
    function ancestorWith(el, attr) {
      var node = el;
      while (node && node.nodeType === 1) {
        if (node.hasAttribute && node.hasAttribute(attr)) return node;
        node = node.parentElement;
      }
      return null;
    }
    function boxOf(el) {
      var r = el.getBoundingClientRect();
      return { x: r.x, y: r.y, width: r.width, height: r.height, top: r.top, left: r.left };
    }
    var TAG_ROLE={h1:"heading",h2:"heading",h3:"heading",h4:"heading",h5:"heading",h6:"heading",button:"button",a:"link",img:"image",picture:"image",svg:"icon",input:"input field",textarea:"input field",select:"dropdown",label:"field label",form:"form",p:"paragraph",span:"text",ul:"list",ol:"list",li:"list item",nav:"navigation",header:"header",footer:"footer",section:"container",article:"container",aside:"container",main:"container",div:"container"};
    var TEXT_TAGS={h1:1,h2:1,h3:1,h4:1,h5:1,h6:1,p:1,a:1,button:1,span:1,li:1,blockquote:1,label:1,strong:1,em:1,small:1,figcaption:1};
    var CARD_RE=/(^|[-_ ])(card|tile)([-_ ]|$)/i;
    function titleCase(s){return s?s.charAt(0).toUpperCase()+s.slice(1):s;}
    function humanize(s){var t=(s||"").replace(/[-_]/g," ").replace(/([a-z0-9])([A-Z])/g,"$1 $2").trim();return t?t.charAt(0).toUpperCase()+t.slice(1):(s||"");}
    function classTokens(el){return (el.getAttribute("class")||"").split(/\s+/).filter(function(t){return t&&t.indexOf("svelte-")!==0;});}
    function roleOf(el){return CARD_RE.test(el.getAttribute("class")||"")?"card":(TAG_ROLE[el.tagName.toLowerCase()]||null);}
    function textOf(el){var tag=el.tagName.toLowerCase();if(tag==="img"){var alt=(el.getAttribute("alt")||"").trim();return alt||null;}if(!TEXT_TAGS[tag])return null;var t=(el.textContent||"").trim();return t||null;}
    function ordinalOf(el,scope){var root=scope||el.ownerDocument;var tag=el.tagName.toLowerCase();var tokens=classTokens(el);var same=Array.prototype.slice.call(root.querySelectorAll(tag));var peers=tokens.length?same.filter(function(p){var pt=classTokens(p);return pt.some(function(t){return tokens.indexOf(t)>=0;});}):same;if(peers.length<=1)return null;var i=peers.indexOf(el);return i>=0?i+1:null;}
    function refOf(target,sectionEl){
      if(!target||target.nodeType!==1)return null;
      var secId=sectionEl?(sectionEl.getAttribute("data-paw-section")||""):"";
      var secLabel=secId?humanize(secId):"";
      var tag=target.tagName.toLowerCase();
      if(sectionEl===target){ if(!secId)return null; return {id:secId,tag:tag,role:null,label:secLabel,text:null,sectionId:secId,sectionLabel:secLabel,ordinal:null,level:"section",boundKind:null}; }
      var ordinal=ordinalOf(target,sectionEl||target.ownerDocument);
      var role=roleOf(target);
      var uid=target.getAttribute("data-uid");
      return {id:uid||(secId+":"+tag+":"+(ordinal||0)),tag:tag,role:role,label:titleCase(role||tag),text:textOf(target),sectionId:secId,sectionLabel:secLabel,ordinal:ordinal,level:"element",boundKind:null};
    }
    function send(msg) {
      msg.nonce = NONCE;
      try { window.parent.postMessage(msg, ORIGIN); } catch (_) {}
    }
    function post(type, sectionEl, leafEl, target) {
      var el = target ? refOf(target, sectionEl) : null;
      send({
        type: type,
        section: sectionEl ? sectionEl.getAttribute("data-paw-section") : null,
        rect: sectionEl ? boxOf(sectionEl) : (leafEl ? boxOf(leafEl) : null),
        uid: leafEl ? leafEl.getAttribute("data-uid") : null,
        uidRect: leafEl ? boxOf(leafEl) : null,
        element: el,
        elementRect: (el && target) ? boxOf(target) : null
      });
    }
    var mode = "select", editEl = null, editUid = "", editSeed = "";
    function byUid(uid) {
      if (typeof uid !== "string" || !uid) return null;
      var all = document.querySelectorAll("[data-uid]");
      for (var i = 0; i < all.length; i++) if (all[i].getAttribute("data-uid") === uid) return all[i];
      return null;
    }
    function soleText(el) {
      if (!el || !el.childNodes || el.childNodes.length !== 1) return null;
      var n = el.childNodes[0];
      return n && n.nodeType === 3 ? n : null;
    }
    function editableUid(el) {
      if (!el || el.nodeType !== 1 || !soleText(el)) return "";
      return el.getAttribute("data-uid") || "";
    }
    function insertPlain(text) {
      text = String(text || "").replace(/[\r\n]+/g, " ");
      if (!text || !editEl) return;
      var done = false;
      try { done = document.execCommand("insertText", false, text); } catch (_) {}
      if (done) return;
      try {
        var s = window.getSelection(), r = s && s.rangeCount ? s.getRangeAt(0) : null;
        if (!r || !editEl.contains(r.commonAncestorContainer)) { r = document.createRange(); r.selectNodeContents(editEl); r.collapse(false); }
        r.deleteContents();
        var tn = document.createTextNode(text); r.insertNode(tn);
        r.setStartAfter(tn); r.collapse(true); s.removeAllRanges(); s.addRange(r);
      } catch (_) { editEl.textContent = (editEl.textContent || "") + text; }
      editEl.normalize();
    }
    function onPaste(ev) {
      ev.preventDefault();
      var t = ev.clipboardData || window.clipboardData;
      insertPlain(t ? t.getData("text/plain") : "");
    }
    function onDrop(ev) {
      ev.preventDefault();
      var t = ev.dataTransfer;
      var text = t ? t.getData("text/plain") : "";
      if (!text) return;
      try {
        var r = document.caretRangeFromPoint ? document.caretRangeFromPoint(ev.clientX, ev.clientY) : null;
        if (!r && document.caretPositionFromPoint) { var p = document.caretPositionFromPoint(ev.clientX, ev.clientY); if (p) { r = document.createRange(); r.setStart(p.offsetNode, p.offset); } }
        if (r && editEl && editEl.contains(r.startContainer)) { var s = window.getSelection(); s.removeAllRanges(); s.addRange(r); }
      } catch (_) {}
      insertPlain(text);
    }
    function onBeforeInput(ev) {
      var k = ev.inputType || "";
      if (k === "insertParagraph" || k === "insertLineBreak" || k.indexOf("format") === 0 || k === "insertFromDrop" || k === "insertFromPaste") ev.preventDefault();
    }
    function endEdit(commit) {
      if (!editEl) return;
      var el = editEl, uid = editUid, seed = editSeed;
      editEl = null; editUid = ""; editSeed = "";
      el.removeEventListener("paste", onPaste, true);
      el.removeEventListener("drop", onDrop, true);
      el.removeEventListener("beforeinput", onBeforeInput, true);
      el.removeAttribute("contenteditable");
      el.removeAttribute("spellcheck");
      var next = el.textContent || "";
      var tn = soleText(el);
      if (!commit) { if (tn) tn.data = seed; else el.textContent = seed; }
      else if (!tn) el.textContent = next;
      var changed = commit && next !== seed;
      if (changed) send({ type: "paw-edit-leaf-text", uid: uid, text: next });
      send({ type: "paw-edit-inline-end", uid: uid, committed: changed });
    }
    function beginEdit(el) {
      var uid = editableUid(el);
      if (!uid) return false;
      if (editEl === el) { send({ type: "paw-edit-inline-begin", uid: uid, ok: true }); return true; }
      endEdit(true);
      editEl = el; editUid = uid; editSeed = el.textContent || "";
      el.setAttribute("contenteditable", "plaintext-only");
      if (el.contentEditable !== "plaintext-only") el.setAttribute("contenteditable", "true");
      el.setAttribute("spellcheck", "false");
      el.addEventListener("paste", onPaste, true);
      el.addEventListener("drop", onDrop, true);
      el.addEventListener("beforeinput", onBeforeInput, true);
      try { el.focus(); } catch (_) {}
      try {
        var r = document.createRange(); r.selectNodeContents(el); r.collapse(false);
        var s = window.getSelection(); s.removeAllRanges(); s.addRange(r);
      } catch (_) {}
      send({ type: "paw-edit-inline-begin", uid: uid, ok: true });
      return true;
    }
    function inEdit(t) { return !!(editEl && t && (t === editEl || (editEl.contains && editEl.contains(t)))); }
    var hlBox = null, hlEl = null;
    function placeBox() {
      if (!hlBox || !hlEl) return;
      var r = hlEl.getBoundingClientRect(), s = hlBox.style;
      s.display = "block"; s.left = r.left + "px"; s.top = r.top + "px"; s.width = r.width + "px"; s.height = r.height + "px";
    }
    function clearHighlight() { hlEl = null; if (hlBox) hlBox.style.display = "none"; }
    function highlight(uid) {
      var el = byUid(uid);
      if (!el) { clearHighlight(); send({ type: "paw-edit-highlighted", uid: typeof uid === "string" ? uid : null, found: false, uidRect: null }); return; }
      if (!hlBox) {
        hlBox = document.createElement("div");
        hlBox.setAttribute("data-paw-edit-overlay", "highlight");
        var s = hlBox.style;
        s.position = "fixed"; s.pointerEvents = "none"; s.boxSizing = "border-box"; s.borderRadius = "3px";
        s.zIndex = "2147483000"; s.border = "2px solid #0a84ff"; s.background = "rgba(10,132,255,0.08)"; s.display = "none";
        document.documentElement.appendChild(hlBox);
      }
      hlEl = el;
      try { if (el.scrollIntoView) el.scrollIntoView({ block: "center", behavior: "smooth" }); } catch (_) {}
      placeBox();
      send({ type: "paw-edit-highlighted", uid: uid, found: true, uidRect: boxOf(el) });
    }
    window.addEventListener("scroll", placeBox, true);
    window.addEventListener("resize", placeBox, true);
    document.addEventListener("mouseover", function (e) {
      if (inEdit(e.target)) return;
      var sec = ancestorWith(e.target, "data-paw-section");
      var leaf = ancestorWith(e.target, "data-uid");
      if (sec || leaf) post("paw-edit-hover", sec, leaf, e.target);
    }, true);
    document.addEventListener("click", function (e) {
      if (inEdit(e.target)) return;
      var sec = ancestorWith(e.target, "data-paw-section");
      var leaf = ancestorWith(e.target, "data-uid");
      if (sec || leaf) { e.preventDefault(); post("paw-edit-click", sec, leaf, e.target); }
    }, true);
    document.addEventListener("dblclick", function (e) {
      if (mode !== "design" || inEdit(e.target)) return;
      var el = e.target;
      while (el && el.nodeType === 1 && el !== document.body && !editableUid(el)) el = el.parentElement;
      if (!el || el.nodeType !== 1 || el === document.body) return;
      e.preventDefault(); e.stopPropagation();
      beginEdit(el);
    }, true);
    document.addEventListener("keydown", function (e) {
      if (!editEl) return;
      if (e.isComposing || e.keyCode === 229) return;
      if (e.key === "Escape") { e.preventDefault(); e.stopPropagation(); endEdit(false); }
      else if (e.key === "Enter") { e.preventDefault(); e.stopPropagation(); if (!e.shiftKey) endEdit(true); }
    }, true);
    document.addEventListener("focusout", function (e) { if (editEl && e.target === editEl) endEdit(true); }, true);
    window.addEventListener("message", function (e) {
      if (e.source !== window.parent || e.origin !== ORIGIN) return;
      var d = e.data;
      if (!d || typeof d !== "object" || d.__pawEditCmd !== true) return;
      if (!NONCE || d.nonce !== NONCE) return;
      if (d.type === "arm") { mode = d.mode === "design" ? "design" : "select"; if (mode !== "design") endEdit(true); }
      else if (d.type === "highlight") highlight(d.uid);
      else if (d.type === "clear-highlight") clearHighlight();
      else if (d.type === "begin-inline-edit") { if (!beginEdit(byUid(d.uid))) send({ type: "paw-edit-inline-begin", uid: typeof d.uid === "string" ? d.uid : null, ok: false }); }
    });
  } catch (_) { /* bridge must never break a public page */ }
})();
