// ee/pocketpaw_ee/sites/runtime_reporter.js --
// the paw-sites runtime-error reporter, put at the top of every html draft page.
//
// Generated by scripts/vendor-paw-sites-edit-bridge.sh from paw-sites a147ea5
// (src/edit-bridge.ts). Do not hand-edit. The quoted "__PAW_BUILDER_ORIGIN__"
// placeholder is replaced with the builder origin by preview_origin.py.

(function () {
  try {
    if (window.parent === window || window.__pawRuntimeReporter) return;
    window.__pawRuntimeReporter = true;
    var TARGET = "__PAW_BUILDER_ORIGIN__";
    var NONCE = new URLSearchParams(window.location.search).get("paw_nonce") || "";
    function report(m) {
      try { window.parent.postMessage({ __pawRuntime: true, nonce: NONCE, type: "error", message: String(m).slice(0, 300) }, TARGET); } catch (_) {}
    }
    window.addEventListener("error", function (e) { report((e && e.message) || "Script error"); });
    window.addEventListener("unhandledrejection", function (e) { var r = e && e.reason; report((r && r.message) || r || "Unhandled rejection"); });
  } catch (_) { /* never break the page */ }
})();
