// ee/pocketpaw_ee/sites/runtime_reporter.js --
// the paw-sites runtime-error reporter, put at the top of every html draft page.
//
// Generated by scripts/vendor-paw-sites-edit-bridge.sh from paw-sites 170a273
// (src/edit-bridge.ts). Do not hand-edit. The quoted "__PAW_BUILDER_ORIGIN__"
// placeholder is replaced with the builder origin by preview_origin.py.

(function () {
  try {
    if (window.parent === window || window.__pawRuntimeReporter) return;
    window.__pawRuntimeReporter = true;
    var TARGET = "__PAW_BUILDER_ORIGIN__";
    var NONCE = new URLSearchParams(window.location.search).get("paw_nonce") || "";
    function emit(msg) {
      msg.__pawRuntime = true; msg.nonce = NONCE;
      try { window.parent.postMessage(msg, TARGET); } catch (_) {}
    }
    function report(m) {
      emit({ type: "error", message: String(m).slice(0, 300) });
    }
    window.addEventListener("error", function (e) { report((e && e.message) || "Script error"); });
    window.addEventListener("unhandledrejection", function (e) { var r = e && e.reason; report((r && r.message) || r || "Unhandled rejection"); });
    var lastPath = null;
    function reportLocation() {
      try {
        var l = window.location, q = new URLSearchParams(l.search);
        q.delete("paw_edit"); q.delete("paw_nonce");
        var qs = q.toString();
        var path = l.pathname + (qs ? "?" + qs : "") + l.hash;
        if (path === lastPath) return;
        lastPath = path;
        emit({ type: "location", path: path });
      } catch (_) {}
    }
    function wrapHistory(name) {
      try {
        var h = window.history, orig = h && h[name];
        if (typeof orig !== "function") return;
        h[name] = function () { var r = orig.apply(this, arguments); reportLocation(); return r; };
      } catch (_) {}
    }
    wrapHistory("pushState"); wrapHistory("replaceState");
    window.addEventListener("popstate", reportLocation);
    window.addEventListener("hashchange", reportLocation);
    reportLocation();
  } catch (_) { /* never break the page */ }
})();
