# ee/pocketpaw_ee/sites/workers_deploy.py — deploy a STATIC Paw Site as a regular
# Cloudflare Worker on the FREE tier (workers.dev) via `wrangler deploy`.
#
# Created: 2026-06-25 (feat/sites-workers-deploy-mode) — the "workers" deploy mode.
#
# Updated 2026-07-12 (feat/sites-html-assets-only-deploy, HE-4) — the deploy is now
# ENGINE-AWARE. An ``engine="html"`` site deploys as an ASSETS-ONLY Worker: the
# generator emits a raw static tree (``static_output_rel("html") == "."``, no
# ``_worker.js``), so the emitted ``wrangler.jsonc`` drops ``main`` + ``nodejs_compat``
# and just serves ``assets.directory: "."`` — a legal no-``main`` Worker that ships
# ZERO bytes of JavaScript for a form-less brochure. Because the asset dir is the
# project ROOT (which also holds ``wrangler.jsonc``), html writes a config-excluding
# ``.assetsignore`` (``wrangler.jsonc`` + ``.assetsignore``) so wrangler does not serve
# the config as a public asset — wrangler only auto-excludes its config when the asset
# dir is a SUBDIR (Cloudflare static-assets docs). ripple/svelte keep the exact
# SvelteKit-worker config + the ``_worker.js`` ``.assetsignore`` (the default engine is
# ``"ripple"``, so every existing caller is byte-for-byte unchanged).
#
# Updated 2026-08-12 (the custom-domain routing lane) — ``_worker_name`` is now the
# PUBLIC ``worker_name``. A custom domain is served by pointing a Cloudflare Worker
# route at the site's Worker, so the control plane needs the same name this module
# deploys under. Cloudflare rejects a route naming a script that does not exist, so
# the two answers must be one function rather than two that agree today.
#
# Updated 2026-09-02 (SA-1 — the visitor counter) — THE ASSETS-ONLY BRANCH NO LONGER
# SHIPS ZERO JAVASCRIPT. The HE-4 note above still says it does; treat that sentence
# as history rather than as the current contract. An
# assets-only site now deploys with a ``main``: the pageview counter generated by
# ``sites/analytics_worker.py``, plus the ``ASSETS`` binding it serves the page
# through, an ``analytics_engine_datasets`` binding, and an ``assets.run_worker_first``
# ALLOW-LIST that keeps every request that is not a page off the Worker entirely.
#
# That allow-list is the load-bearing part. Cloudflare bills a Worker invocation and
# serves a static asset free, so a rule matching a page's ~20 subresources multiplies
# the per-pageview cost by about twenty. The rules, the wrangler constraints they
# satisfy and the reason they are an allow-list rather than a deny-list all live in
# ``analytics_worker.py``; this module only asks it for them.
#
# The generated entry is written at the PROJECT ROOT and listed in the assets-only
# ``.assetsignore``. That line is a privacy control, not housekeeping: an html site's
# asset dir IS the project root, so an unignored entry is uploaded and the per-publish
# hash salt baked into it becomes publicly downloadable.
#
# The server-worker branch (ripple / dynamic svelte) is UNCHANGED — its config carries
# no counter, because ``main`` there is already SvelteKit's own worker and a second
# entry cannot be bolted in front of it from a config key. That is a later slice.
#
# Updated 2026-09-02 (SA-3 — the shim) — THAT LATER SLICE IS THIS ONE, and the sentence
# above is now history: a ripple / dynamic-svelte publish counts too. The step it was
# missing is that a second entry cannot be bolted in front of the SvelteKit worker FROM
# A CONFIG KEY, but it can from a MODULE. ``analytics_worker.build_shim_js`` generates
# one that imports the adapter's ``_worker.js``, wraps its ``fetch`` and delegates, and
# the config points ``main`` at the shim instead. The adapter's own file is never
# edited — the adapter regenerates it on every build, so an edit would survive exactly
# one build.
#
# THE COUNTING SERVER-WORKER CONFIG ALSO GAINS ``run_worker_first``, and without it this
# slice would count nothing. With a ``main`` and an ``assets`` block and no routing
# rules, Cloudflare's asset router serves an EXISTING asset directly and only falls
# through to the Worker when none matches — which is exactly how a ripple site's
# prerendered ``index.html`` is served today, without ever invoking the worker. The
# shim would have seen SSR routes and nothing else. The rules are the same page
# allow-list ``analytics_worker`` builds for the assets-only branch, over the adapter's
# output dir, so subresources stay on the free path; the cost model in that module
# governs both branches now.
#
# Routing a prerendered page through the worker is safe rather than merely acceptable:
# adapter-cloudflare's worker checks its own prerendered manifest first and answers
# from ``env.ASSETS.fetch(req)``, so the page it serves is the same file the asset
# router would have served.
#
# ``nodejs_compat``, the ``ASSETS`` binding and any D1 binding are carried through
# untouched. A dynamic site's remote functions still reach their database; the shim
# only changes which module is the entry.
#
# ONE COMMENT ELSEWHERE IS NOW FALSE, and it is named here because a stale comment
# asserting something is IMPOSSIBLE is worse than no comment — the next reader believes
# it. ``sites.service._deploy_dynamic_site`` (the provision lane) passes
# ``analytics_entitled=False`` unconditionally, and says it does so because no counter
# can be bolted in front of the SvelteKit worker from a config key. That reason no
# longer holds: a module can do what a config key could not, and this file is where it
# is done. The lane still counts nothing, which is a FOLLOW-UP rather than a bug in
# this slice.
#
# The follow-up is deliberately not bundled here, and the ordering is the reason.
# Flipping that lane to pass a resolved entitlement is only safe once the shim exists —
# doing both at once could deploy a config naming a shim that is not there. It lands
# after this, not beside it. Until then the main publish seam
# (``_deploy_site_doc``) is the lane that counts, and it already passes the resolved
# entitlement for every engine.
#
# Updated 2026-09-02 (SA-2 — the gate) — THE COUNTER IS NO LONGER UNCONDITIONAL. SA-1
# wired it onto every assets-only publish; a Worker invocation is billed and a static
# asset is not, so that spent money on sites paying nothing. ``_write_deploy_files``
# now takes ``analytics_entitled`` — the site's plan, resolved at the publish seam by
# ``entitlements.site_analytics_entitled`` — ANDs it with the operator kill switch
# ``PAW_SITES_ANALYTICS_DISABLED``, and writes ONE of two shapes.
#
# THE OFF SHAPE IS THE PRE-ANALYTICS CONFIG, BYTE FOR BYTE: no ``main``, no dataset
# binding, no ``run_worker_first``, and an ``assets`` block of nothing but
# ``directory`` — not even the ``ASSETS`` binding SA-1 added, because there is no
# entry to bind it for. That exactness is the point of the kill switch rather than a
# nicety: an operator pulling it in an incident is asking for the config that was
# proven before analytics existed, and "nearly that config" is not a rollback.
#
# The entry file is DELETED, not merely skipped, whenever counting is off. A publish
# reuses the pocket's working dir, so a site that published paid and then publishes
# free still has the earlier entry on disk — and with no ``main`` naming it, wrangler
# uploads it as an ordinary asset and serves the per-publish salt to anyone who asks.
# The ``.assetsignore`` still lists it on every assets-only publish for the same
# reason, counting or not.
#
# Updated 2026-08-07 (RX-1 — the react engine) — the assets-only branch now keys on
# ``emits_server_worker(engine)`` instead of ``not needs_node_build(engine)``. Those
# two questions had the same answer for ripple/svelte/html, so the old condition read
# correctly by coincidence. ``engine="react"`` breaks the coincidence: it runs a full
# ``bun install`` + Vite build and STILL emits no server entry, because that build is
# an SSG that prerenders to a static ``dist/``. Under the old condition react would
# have taken the SvelteKit branch and written ``main: "dist/_worker.js"`` for a file
# no react build produces, failing the deploy on a missing ``main``. So react joins
# html on the assets-only path — with ``assets.directory: "dist"`` — and the question
# this module asks is now about the OUTPUT SHAPE, never about how it was produced.
#
# This is the third deploy target for a Paw Site, beside the LOCAL static server
# (local_server.deploy_local — dev/smoke) and Workers-for-Platforms
# (cloudflare_client.put_worker — the multi-tenant dispatch namespace). The
# "workers" mode publishes a static site as an ordinary Worker on a free
# workers.dev subdomain, which needs NO WfP dispatch namespace, NO D1, NO Queue —
# just a Cloudflare account token. It is the cheapest path to a real public URL and
# the one PROVEN live by the manual recipe this module automates.
#
# THE RECIPE (verified live — a real paw site serves on workers.dev with exactly
# this). After the generator emits ``<project>/.svelte-kit/cloudflare/`` (the
# adapter-cloudflare static output: ``_worker.js`` + the ``_app/...`` asset tree),
# two files make it deployable to workers.dev with wrangler 4.x:
#   1. ``<project>/.svelte-kit/cloudflare/.assetsignore`` — REQUIRED. wrangler 4.x
#      HARD-ERRORS ("Uploading a Pages _worker.js file as an asset") if the worker
#      entry sits inside the asset dir without it, and adapter-cloudflare does NOT
#      emit it. The RECIPE lines are ``_worker.js`` / ``_routes.json`` / ``_headers``;
#      SA-3 appends the two generated counter filenames, which are named on every
#      publish whether or not one was written (see ``_COUNTER_FILENAMES``).
#   2. ``<project>/wrangler.jsonc`` — the clean static config: ``main`` →
#      ``.svelte-kit/cloudflare/_worker.js``, ``assets.directory`` → the SAME dir,
#      ``workers_dev: true``, ``nodejs_compat``. SA-3 — when the site COUNTS, ``main``
#      is the generated shim at the project root instead, and it is the shim that
#      imports ``_worker.js``. Everything else in this recipe is unchanged.
#      We do NOT reuse the generator's own
#      ``wrangler.toml`` (it stamps an UNDERSCORE name variant + D1/Queue bindings
#      for the dynamic path — invalid for a clean static worker).
# Deploy: ``bunx wrangler@4.101.0 deploy`` with ``CLOUDFLARE_API_TOKEN`` +
# ``CLOUDFLARE_ACCOUNT_ID`` in the env. wrangler prints the deployed
# ``https://<name>.<account-subdomain>.workers.dev`` URL on stdout; we parse it
# (falling back to constructing it from PAW_CF_WORKERS_SUBDOMAIN if the parse fails).
#
# HARD RULES from the live test:
#   * Worker/subdomain names MUST match ``^[a-z0-9][a-z0-9-]*$`` (lowercase,
#     hyphens; NO underscores). The site_id is a 24-hex ObjectId (already
#     lowercase-safe), so the name is ``paw-site-<site_id>``. ``_sanitize`` guards a
#     non-conforming id so a bad id can never produce an invalid name.
#   * STATIC sites ONLY. A DYNAMIC site (pattern=="dynamic", or a spec carrying
#     live bindings) needs a per-tenant D1 + Queues provisioned — that is Phase 2.
#     In workers mode a dynamic site raises a clean ``ValidationError`` rather than
#     deploying a broken site that can't reach its data.
#
# The wrangler invocation is overridable via PAW_CF_WRANGLER_CMD (default
# ``bunx wrangler@4.101.0``) so it is pinnable, ``shlex.split`` like
# PAW_SITES_GEN_CMD. The subprocess style mirrors generator_client.py
# (``asyncio.create_subprocess_exec``, captured stdout/stderr, non-zero → raise
# with the stderr tail).

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import secrets
from pathlib import Path

from pocketpaw_ee.cloud._core.errors import Internal, ValidationError
from pocketpaw_ee.sites import analytics_worker
from pocketpaw_ee.sites._wrangler import wrangler_argv as _wrangler_argv
from pocketpaw_ee.sites.engines import (
    resolve_emits_server_worker,
    resolve_static_output_rel,
)

logger = logging.getLogger(__name__)

# The static-output dir adapter-cloudflare emits for a ripple/svelte build, relative
# to the project dir. The worker entry AND the asset tree both live here. Retained as
# a named constant for readability; the config is now driven off
# ``static_output_rel(engine)`` (HE-4), which resolves to this for ripple/svelte and
# to ``"."`` for html (whose raw static tree IS the project dir).
_CF_OUTPUT_REL = ".svelte-kit/cloudflare"

# BOTH generated counters, named in EVERY .assetsignore this module writes, on both
# branches, whether or not this publish counts. One constant rather than a line in each
# list, so the two can never disagree about which files are deploy scaffold.
#
# The unconditional part is what makes the stale-counter delete in ``_write_deploy_files``
# safe to swallow: the delete may fail (a lock, a read-only file), and a file left on
# disk is still excluded from the upload. Whichever counter this publish did not write
# is a per-publish hash salt with no config naming it, and wrangler would otherwise
# upload it as an ordinary static asset — see the privacy note in ``analytics_worker``.
#
# On the ASSETS-ONLY branch that exclusion is load-bearing: an html site's asset dir IS
# the project root, so a leftover counter sits inside the served tree. On the
# SERVER-WORKER branch both counters live at the project root while the asset dir is
# ``.svelte-kit/cloudflare``, so nothing there could be uploaded anyway and the lines
# are belt-and-braces. They are written all the same, because "the counters are named
# on every publish" is an invariant worth being able to state without a caveat, and a
# name that matches no file is a no-op.
_COUNTER_FILENAMES = (
    analytics_worker.ENTRY_FILENAME,
    analytics_worker.SHIM_FILENAME,
)

# The REQUIRED .assetsignore contents for a ripple/svelte (server-worker) deploy. Drops
# the Pages-style worker/routing/header files so wrangler 4.x does not try to upload the
# worker entry as a static asset (which it HARD-ERRORS on). adapter-cloudflare does not
# emit this file, so the deploy step writes it. SA-3 appends the counter filenames above.
_ASSETSIGNORE_LINES = ("_worker.js", "_routes.json", "_headers") + _COUNTER_FILENAMES

# The .assetsignore contents for an ASSETS-ONLY deploy (html, react — anything with
# no ``_worker.js``). An html site's ``assets.directory`` is the project ROOT
# (``static_output_rel("html") == "."``), which also holds the deploy scaffold —
# ``wrangler.jsonc`` and this ``.assetsignore`` — so wrangler would otherwise upload
# the config file as a public asset (it only auto-excludes the config when the asset
# dir is a SUBDIR, per the Cloudflare static-assets docs). There is no ``_worker.js``
# on these paths; the exclusion is the config files, not a server entry.
#
# react's asset dir IS a subdir (``dist``), so wrangler already excludes the config —
# but ``.assetsignore`` itself is written INSIDE the asset dir on every engine, and
# excluding it is what stops it being served. Naming a ``wrangler.jsonc`` that isn't
# in ``dist/`` is a harmless no-op, so both engines share one list rather than
# maintaining a near-identical second one.
#
# SA-1 added the generated counter entry, and that third line is the one with teeth.
# The entry carries the per-publish salt the visitor hash is built on; served as a
# public asset it hands out the salt, and the hash stops being irreversible. Removing
# this line does not break a deploy — it breaks the privacy claim, silently.
#
# SA-2 — that line is written on EVERY assets-only publish, including the ones that
# deploy no counter at all. Naming a file that is not there is a no-op (the same
# reason both engines share this one list), and the case it covers is real: a site
# that publishes paid and then free reuses the working dir, so a leftover entry can
# still be sitting in it. ``_write_deploy_files`` deletes that leftover; this line is
# what stands if the delete ever stops happening.
_ASSETS_ONLY_ASSETSIGNORE_LINES = (
    "wrangler.jsonc",
    ".assetsignore",
) + _COUNTER_FILENAMES

# wrangler reads the worker name + name-segment of the workers.dev URL from
# ``wrangler.jsonc``'s ``name``. It must match this (lowercase alnum + hyphen,
# leading alnum). The recipe names a site ``paw-site-<site_id>``; the 24-hex
# ObjectId is already lowercase-safe, so this is really a guard against a
# non-ObjectId id slipping through.
_WORKER_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")

# The pinned wrangler invocation. Overridable (and ``shlex.split``) via
# The wrangler invocation (PAW_CF_WRANGLER_CMD, default `bunx wrangler@4.101.0`) is
# resolved by the shared, Windows-safe helper (imported at top as _wrangler_argv) so
# deploy + D1-migrate share one seam. See _wrangler.py for the `bunx`->`bun x` rewrite
# that keeps it launchable on Windows.


def _sanitize(raw: str) -> str:
    """Coerce an arbitrary id into a valid worker-name SEGMENT: lowercase, with any
    run of disallowed chars (incl. underscores) collapsed to a single hyphen, and
    leading/trailing hyphens stripped. A 24-hex ObjectId passes through unchanged
    (already lowercase + hyphen-free); this only ever bites a non-ObjectId id. Falls
    back to ``"site"`` if sanitizing leaves an empty string, so the name is never
    invalid."""
    s = raw.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")
    return s or "site"


# The D1 binding name a dynamic site's remote functions read (``platform.env.DB``).
# Must match the WfP path's binding so the SAME built worker runs on either target.
_D1_BINDING_NAME = "DB"

# We write our own config, but a DYNAMIC project dir ALSO carries the generator's
# wrangler.toml (name + d1 + queue producers, aimed at the WfP upload). Two configs
# in one dir is ambiguous, so every wrangler invocation names ours explicitly.
_CONFIG_FILENAME = "wrangler.jsonc"


def worker_name(site_id: str) -> str:
    """The worker / workers.dev subdomain name for a site: ``paw-site-<site_id>``,
    sanitized so it always matches ``^[a-z0-9][a-z0-9-]*$`` (CF rejects underscores
    + uppercase). The ``paw-site-`` prefix starts with a letter, so the leading-char
    rule holds regardless of the (sanitized) id.

    PUBLIC since 2026-08-12 (was ``_worker_name``): the custom-domain lane needs the
    same answer to point a Worker route at a site, and a second copy of this rule
    living in the service layer would drift from the one the deploy actually uses.
    A route naming a script that does not exist is rejected by Cloudflare, so the two
    must agree exactly."""
    return f"paw-site-{_sanitize(site_id)}"


# Back-compat alias — the private name predates the route lane and is still what the
# deploy path reads below.
_worker_name = worker_name


def _wrangler_jsonc(
    name: str,
    engine: str = "ripple",
    d1_database_id: str | None = None,
    *,
    project_dir: str | os.PathLike[str],
    count_pageviews: bool = True,
) -> str:
    """The clean wrangler config for a workers.dev deploy (the proven recipe).

    HE-4 — the config is ENGINE-AWARE. RX-1 — it keys on whether a server entry was
    emitted, NOT on ``needs_node_build``. SL-1 — it now asks that of the ARTIFACT
    (``resolve_emits_server_worker``) rather than of the engine name, because a static
    svelte site emits no worker while a dynamic one does:

    * html / react / STATIC svelte (no worker emitted) → an ASSETS-ONLY Worker. The
      build output is a static tree with no ``_worker.js``, so the config carries no
      ``nodejs_compat`` and serves ``assets.directory`` (``"."`` for html, ``"dist"``
      for react, ``build`` for static svelte). SA-1 — it carries a ``main`` WHEN THE
      SITE COUNTS: the generated pageview counter, plus the ``ASSETS`` binding it
      serves through, the analytics dataset binding, and the ``run_worker_first``
      allow-list that keeps stylesheets, scripts, fonts and images off the Worker.
      The counter is not the SvelteKit worker under another name; ``main`` still
      never points into the build output.
    * ripple / DYNAMIC svelte (worker emitted) → the SvelteKit Cloudflare worker.
      ``assets.directory`` points at the adapter's output dir
      (``.svelte-kit/cloudflare``), which is also where the worker entry sits (the
      ``.assetsignore`` we write keeps wrangler from uploading it as an asset).
      ``nodejs_compat`` is what the SvelteKit worker needs at runtime. SA-3 — WHEN THE
      SITE COUNTS, ``main`` moves to the generated SHIM at the project root, which
      imports that worker and delegates to it; ``nodejs_compat``, the ``ASSETS``
      binding and any D1 binding are carried through unchanged, and the config also
      gains the dataset binding and the ``run_worker_first`` page allow-list. Without
      those rules the asset router would serve every prerendered page itself and the
      shim would never run — see the header.

    Why the predicate changed: until react, "runs a Node build" and "emits a server
    entry" were the same set, so ``needs_node_build`` read correctly here by
    coincidence. react runs a full Vite build and prerenders to a purely static
    ``dist/`` — asking the build question would have written ``main:
    "dist/_worker.js"`` for a file that is never generated, and wrangler fails the
    deploy on a missing ``main``.

    ``workers_dev: true`` publishes to the free ``<name>.<subdomain>.workers.dev`` URL.

    ``d1_database_id`` (DYNAMIC sites — ripple/svelte only) adds the single ``DB`` D1
    binding — the same binding WfP's ``put_worker`` passes — so a dynamic site's
    remote functions reach their per-tenant database on the FREE tier. Dynamic html is
    out of scope (it has no server runtime), so an html config never carries a binding.

    ``count_pageviews`` (SA-2) picks between the two shapes on EITHER branch (SA-3 —
    it used to reach only the assets-only one): True is the counting config above,
    False is the PRE-ANALYTICS config byte for byte. It is the
    already-resolved answer — the site's plan ANDed with the operator kill switch, via
    ``analytics_worker.counting_enabled`` in ``_write_deploy_files`` — and NOT a
    question this function re-asks, so there is exactly one place that decides.

    It DEFAULTS TO TRUE, which is worth naming rather than leaving to be discovered.
    This is a private config builder whose only production caller passes an explicitly
    resolved value; the default keeps the direct-call tests (and the SA-1 shape they
    pin) reading as the subject rather than the exception. The gate that actually
    protects revenue is at the publish seam, and it is asserted end-to-end there — a
    default here can never be what decides whether a free site counts, because the one
    caller always passes.

    Deliberately still NO Queue bindings. The generator's own wrangler.toml declares
    ``LEADS_QUEUE`` / ``WRITEBACK_QUEUE`` producers, but Cloudflare Queues is a paid
    feature and those queues are not created on this path — declaring a producer for
    a nonexistent queue fails the deploy outright. Both consumers already degrade
    gracefully on a missing binding (``api/submit`` forwards straight to the capture
    API; ``writeback.ts`` warns and skips), so omitting them costs durability
    buffering, never a dropped lead."""
    # SL-1 — ``project_dir`` is REQUIRED and keyword-only rather than defaulted. Both
    # facts below are now properties of the emitted artifact, not of the engine string
    # (a static svelte site has no worker and a different output dir), so a default
    # would let a caller silently get the pre-SL-1 answer. Keyword-only because it is
    # not the subject of this function — the name is — and a positional would read as
    # the output path rather than the project root.
    output_rel = resolve_static_output_rel(project_dir, engine)
    # html / react — and, since SL-1, a STATIC svelte site: an assets-only Worker. The
    # build emitted no server script, so still no ``nodejs_compat`` and no D1 (nothing
    # here runs a site's own server code). SA-1 puts the pageview counter in front of
    # the static tree: ``main`` is OUR generated entry at the project root, never
    # anything from the build output.
    #
    # ``run_worker_first`` is the cost floor and is not optional — without it the
    # asset router would send every request, subresources included, through the
    # Worker. ``analytics_worker`` owns the rules and the reasoning; the ``ASSETS``
    # binding is what the entry serves the page through once it has counted.
    #
    # SA-2 — ``count_pageviews`` selects between the two shapes, and the FALSE one is
    # written to be the pre-analytics config EXACTLY: no ``main``, no dataset binding,
    # no routing rules, and an ``assets`` block of nothing but ``directory``. Not even
    # the ``ASSETS`` binding, which SA-1 added — a free site's config has no entry to
    # bind it for, and a spare binding is a difference a byte-for-byte comparison
    # would find. The two shapes are built as separate literals rather than one dict
    # with keys popped off it, because "which keys does the un-analytics config have"
    # is then something a reader can see rather than replay.
    if not resolve_emits_server_worker(project_dir, engine):
        if not count_pageviews:
            return (
                json.dumps(
                    {
                        "name": name,
                        "compatibility_date": "2024-09-23",
                        "workers_dev": True,
                        "assets": {"directory": output_rel},
                    },
                    indent=2,
                )
                + "\n"
            )
        config: dict[str, object] = {
            "name": name,
            "main": analytics_worker.ENTRY_FILENAME,
            "compatibility_date": "2024-09-23",
            "workers_dev": True,
            "assets": {
                "binding": "ASSETS",
                "directory": output_rel,
                "run_worker_first": analytics_worker.run_worker_first_rules(
                    Path(project_dir, output_rel)
                ),
            },
            "analytics_engine_datasets": [
                {
                    "binding": analytics_worker.DATASET_BINDING,
                    "dataset": analytics_worker.dataset_name(),
                }
            ],
        }
        return json.dumps(config, indent=2) + "\n"

    # SA-3 — the server-worker branch counts too, and the counting shape is this same
    # config with ``main`` MOVED: the generated shim at the project root, which imports
    # ``<output_rel>/_worker.js`` and delegates to it. Everything the SvelteKit worker
    # needs at runtime rides along untouched — ``nodejs_compat``, the ``ASSETS`` binding
    # it reads prerendered pages and static files through, and (below) the D1 binding a
    # dynamic site's remote functions reach their database by. Losing any of those would
    # trade a working dynamic site for a counted broken one.
    #
    # ``run_worker_first`` IS NOT OPTIONAL HERE EITHER, for the opposite reason to the
    # assets-only branch. There it stops the Worker being invoked for subresources; here
    # it is what causes the Worker to be invoked for pages AT ALL. With a ``main`` and no
    # rules the asset router serves any request whose asset exists — which for a ripple
    # site is every prerendered page — and only falls through to the Worker when none
    # matches. The shim would have seen SSR routes and nothing else, and counted almost
    # nothing while looking deployed. The rules are the same page allow-list, over the
    # same builder, so the cost floor is unchanged: subresources still route to the
    # free asset path.
    if not count_pageviews:
        config = {
            "name": name,
            "main": f"{output_rel}/_worker.js",
            "compatibility_date": "2024-09-23",
            "compatibility_flags": ["nodejs_compat"],
            "workers_dev": True,
            "assets": {"binding": "ASSETS", "directory": output_rel},
        }
    else:
        config = {
            "name": name,
            "main": analytics_worker.SHIM_FILENAME,
            "compatibility_date": "2024-09-23",
            "compatibility_flags": ["nodejs_compat"],
            "workers_dev": True,
            "assets": {
                "binding": "ASSETS",
                "directory": output_rel,
                "run_worker_first": analytics_worker.run_worker_first_rules(
                    Path(project_dir, output_rel)
                ),
            },
            "analytics_engine_datasets": [
                {
                    "binding": analytics_worker.DATASET_BINDING,
                    "dataset": analytics_worker.dataset_name(),
                }
            ],
        }
    if d1_database_id:
        config["d1_databases"] = [
            {"binding": _D1_BINDING_NAME, "database_name": name, "database_id": d1_database_id}
        ]
    return json.dumps(config, indent=2) + "\n"


# The workers.dev URL wrangler prints on a successful deploy, e.g.
# ``https://paw-site-abc.my-acct.workers.dev``. We parse the FIRST such URL out of
# stdout; the fallback constructs it from PAW_CF_WORKERS_SUBDOMAIN when the parse
# fails (a wrangler output format change must not lose the URL).
_WORKERS_DEV_URL_RE = re.compile(r"https://[a-z0-9][a-z0-9.-]*\.workers\.dev\S*")


def _parse_deploy_url(stdout: str, *, name: str) -> str:
    """Pull the deployed ``https://...workers.dev`` URL out of wrangler's stdout.

    wrangler prints the published URL on success; we return the FIRST workers.dev
    URL it emits. When the parse fails (no match — e.g. a wrangler output-format
    change), construct the canonical URL from the worker name + the account's
    workers.dev subdomain (PAW_CF_WORKERS_SUBDOMAIN). The fallback returns ``""``
    only when the subdomain is also unconfigured, so the caller still gets a
    successful deploy (just without a resolved URL to store)."""
    m = _WORKERS_DEV_URL_RE.search(stdout)
    if m:
        return m.group(0).rstrip(".,)\"'")
    subdomain = os.environ.get("PAW_CF_WORKERS_SUBDOMAIN", "").strip()
    if subdomain:
        return f"https://{name}.{subdomain}.workers.dev"
    return ""


def _write_deploy_files(
    project_dir: str,
    name: str,
    engine: str = "ripple",
    d1_database_id: str | None = None,
    *,
    site_id: str = "",
    analytics_entitled: bool = True,
) -> None:
    """Write the recipe files into the project: an ``.assetsignore`` inside the asset
    dir + the clean ``wrangler.jsonc`` at the project root, and — on the assets-only
    branch — the generated pageview counter the config names as ``main``. All are
    overwritten on a re-publish so a stale config or a stale counter can never linger.

    HE-4 — engine-aware. SL-1 — ARTIFACT-aware: the asset dir is
    ``resolve_static_output_rel(project_dir, engine)`` (``.svelte-kit/cloudflare`` for
    ripple and dynamic svelte, ``build`` for static svelte, ``"."`` for html, ``"dist"``
    for react). The ``.assetsignore`` differs by whether a server entry was actually
    emitted (RX-1 — not ``needs_node_build``; SL-1 — resolved, not predicted):

    * ripple / dynamic svelte → drops the Pages worker entry (``_worker.js`` + friends)
      so wrangler does not upload the server entry as a static asset.
    * html / react / static svelte → there is no server entry to hide; what must not be
      served is the
      deploy scaffold itself (``wrangler.jsonc`` + ``.assetsignore``). For html the
      asset dir IS the project root, so both files sit in it; for react only
      ``.assetsignore`` does, and naming the other is a harmless no-op.

    ``d1_database_id`` adds the dynamic site's D1 binding to the emitted config
    (ripple/svelte only).

    ``site_id`` is what the counter stamps as the Analytics Engine index — the ONE
    index a data point may carry, and therefore the only thing the dataset can be
    queried by. Keyword-only, because it is not this function's subject (the project
    dir is) and a fourth positional string beside ``name``, ``engine`` and the D1 id
    would be read wrong at a glance. It defaults to empty for the server-worker
    branch, which writes no counter at all. The counter is written REGARDLESS of
    whether the id is empty: skipping it would leave the emitted ``main`` pointing at
    a file that is not there, and wrangler fails a deploy on a missing ``main``. An
    empty id costs unqueryable rows; the only caller always has a real one.

    ``analytics_entitled`` (SA-2) is the SITE's half of the counting decision, as
    resolved by ``entitlements.site_analytics_entitled`` at the publish seam. The
    operator kill switch is the other half and is read here, not passed, because it is
    global and per-publish: ``analytics_worker.counting_enabled`` ANDs the two, and its
    answer decides BOTH what the config names as ``main`` and which counter file exists
    on disk. Those two must move together — a config naming an absent ``main`` fails
    the deploy, and a counter with no config naming it is a salt served as a static
    asset.

    SA-3 — the answer now reaches BOTH branches, and the two write different files.
    Assets-only writes ``analytics_worker.ENTRY_FILENAME``, which serves the page
    through ``ASSETS`` after counting. Server-worker writes
    ``analytics_worker.SHIM_FILENAME``, which imports the worker adapter-cloudflare
    emitted and delegates to it — the adapter's ``_worker.js`` is never touched, since
    the adapter rewrites it on every build. Whichever this publish did not write is
    deleted, because a working dir is reused across publishes and across a change of
    build shape.

    WHEN COUNTING IS OFF THE ENTRY IS DELETED rather than merely not written, and that
    is not tidiness. A publish reuses the pocket's working dir, so a site that
    published paid and then publishes free still has the earlier entry on disk. The
    free config names no ``main``, so wrangler would upload that leftover as an
    ordinary asset and hand out the per-publish salt from a config that mentions
    nothing. The ``.assetsignore`` names the entry on EVERY assets-only publish,
    counting or not, as the second line of defence behind the delete.

    THE DELETE CANNOT FAIL A PUBLISH. It is wrapped, because ``missing_ok`` covers
    only the missing file and a locked or read-only one raises. Nothing in the
    analytics path may cost a site its publish, and the ``.assetsignore`` line above
    is what makes swallowing safe rather than merely convenient. The counter WRITE on
    the other branch is deliberately NOT wrapped: the config is about to name that
    file as ``main``, and wrangler fails a deploy on a missing ``main``, so a swallow
    there would trade a clear error for a confusing one."""
    # SL-1 — RESOLVED against the artifact, not predicted from the engine name. A
    # static svelte site builds on adapter-static: its output is ``build`` and it emits
    # no ``_worker.js``, so it must deploy assets-only exactly as react does. Answering
    # either question from ``engine`` alone would point ``main`` at a nonexistent
    # ``build/_worker.js`` AND pick the server-entry .assetsignore — a failed deploy,
    # which is the same class of bug RX-1 added ``emits_server_worker`` to prevent.
    output_rel = resolve_static_output_rel(project_dir, engine)
    out_dir = Path(project_dir, output_rel)
    if not out_dir.is_dir():
        # The static output must exist before this runs — generator.build() emits it.
        # If it is missing the deploy can't proceed (nothing to upload).
        raise ValidationError(
            "sites.workers_no_build",
            "The static build output is missing — the site must be built before a workers deploy.",
        )
    emits_worker = resolve_emits_server_worker(project_dir, engine)
    ignore_lines = _ASSETSIGNORE_LINES if emits_worker else _ASSETS_ONLY_ASSETSIGNORE_LINES
    (out_dir / ".assetsignore").write_text("\n".join(ignore_lines) + "\n")
    # SA-2 — the whole counting decision, resolved once and read twice below so the
    # config and the file on disk can never disagree. SA-3 — it no longer excludes the
    # server-worker branch: that branch now gets a SHIM IN FRONT OF SvelteKit's worker
    # rather than a counter in place of it, so the plan is the only thing that decides.
    count_pageviews = analytics_worker.counting_enabled(entitled=analytics_entitled)
    # WHICH counter, and therefore which file is stale. The assets-only entry serves the
    # page itself through ``ASSETS``; the shim imports the worker the adapter emitted
    # and delegates to it. Neither can stand in for the other — the shim cannot even
    # load in a project with no ``_worker.js``, and the entry would drop a dynamic
    # site's server rendering entirely — so exactly one is written and the other is
    # removed below.
    counter_path = Path(
        project_dir,
        analytics_worker.SHIM_FILENAME if emits_worker else analytics_worker.ENTRY_FILENAME,
    )
    if count_pageviews:
        # The counter the config names as ``main``. Written BEFORE the config so a
        # crash between the two leaves a project with no config rather than one naming
        # an entry that isn't there. The salt is minted here, fresh per publish — see
        # the privacy note in ``analytics_worker`` — and once, so both generators stamp
        # the same one and neither call can quietly get its own.
        secret = secrets.token_hex(16)
        counter_path.write_text(
            analytics_worker.build_shim_js(site_id=site_id, secret=secret, output_rel=output_rel)
            if emits_worker
            else analytics_worker.build_entry_js(site_id=site_id, secret=secret),
            encoding="utf-8",
        )
    # EVERYTHING THIS PUBLISH DID NOT WRITE. Two leftovers are possible in a working dir
    # that publishes over and over: the counter from a paid publish that is now free,
    # and the OTHER branch's counter from before this site's build changed shape (an
    # engine change, or a svelte site that stopped emitting a server entry). Neither is
    # named by the config about to be written, so each is a per-publish salt that
    # wrangler would upload as an ordinary static asset.
    #
    # FAILURE-SOFT, and this is the one delete on the publish path so it is worth
    # saying why it may swallow. ``missing_ok`` covers only the missing file; a
    # read-only file, a Windows lock held by another process, and a directory
    # sitting where the counter should be all raise ``PermissionError`` — and an
    # unwrapped raise here fails the whole publish of a site that is otherwise
    # perfectly fine, over analytics the site may not even be using.
    #
    # Swallowing is safe ONLY because of the ``.assetsignore`` above: it names BOTH
    # counter filenames on every publish, and it is written BEFORE this runs. So a
    # delete that fails leaves the file on disk and still excluded from the upload,
    # which is the whole point of keeping those lines unconditional. Move the
    # ``.assetsignore`` write after this block and the swallow stops being safe.
    #
    # The counter WRITE above is deliberately NOT wrapped: the config is about to name
    # that file as ``main``, and wrangler fails a deploy on a missing ``main``, so a
    # swallow there would trade a clear error for a confusing one.
    for stale_path in (
        Path(project_dir, analytics_worker.ENTRY_FILENAME),
        Path(project_dir, analytics_worker.SHIM_FILENAME),
    ):
        if count_pageviews and stale_path == counter_path:
            continue
        try:
            stale_path.unlink(missing_ok=True)
        except OSError:
            logger.warning(
                "sites.workers: could not remove the stale analytics entry at %s — "
                "publishing anyway; .assetsignore still excludes it from the upload",
                stale_path,
                exc_info=True,
            )
    Path(project_dir, _CONFIG_FILENAME).write_text(
        _wrangler_jsonc(
            name,
            engine,
            d1_database_id,
            project_dir=project_dir,
            count_pageviews=count_pageviews,
        )
    )


def _cf_env() -> dict[str, str]:
    """The subprocess env for wrangler: the current env plus the two CF vars
    wrangler reads itself (``CLOUDFLARE_API_TOKEN`` + ``CLOUDFLARE_ACCOUNT_ID``).
    We pass the full ``os.environ`` through (so PATH / HOME / bun caches resolve)
    and let wrangler pick up the CF creds from it. The vars are NOT logged."""
    return dict(os.environ)


async def deploy_workers(
    site_id: str,
    project_dir: str,
    *,
    engine: str = "ripple",
    d1_database_id: str | None = None,
    analytics_entitled: bool = True,
) -> str:
    """Deploy a Paw Site as a regular Worker on the free workers.dev tier.

    Writes the recipe files (``.assetsignore`` + ``wrangler.jsonc``) into the
    already-built project, then runs ``wrangler deploy`` (PAW_CF_WRANGLER_CMD, default
    ``bunx wrangler@4.101.0``) with the CF creds in the env, and returns the deployed
    ``https://<name>.<subdomain>.workers.dev`` URL (parsed from wrangler's stdout,
    falling back to constructing it from PAW_CF_WORKERS_SUBDOMAIN).

    HE-4 / RX-1 — ``engine`` selects the config shape, via ``emits_server_worker``.
    html and react deploy as an ASSETS-ONLY Worker (no ``_worker.js``, an
    ``assets.directory`` of ``"."`` and ``"dist"`` respectively, and an
    ``.assetsignore`` that keeps the deploy scaffold out of the served tree);
    ripple/svelte deploy the SvelteKit Cloudflare worker unchanged. The default
    (``"ripple"``) preserves the exact prior behaviour for every existing caller —
    svelte resolves to the same ``.svelte-kit/cloudflare`` output.

    SA-1 — the assets-only shape now also writes the generated pageview counter and
    names it as ``main``. ``site_id`` is the Analytics Engine index it stamps, which
    is what makes a site's traffic queryable; the ``run_worker_first`` allow-list in
    the emitted config is what keeps that counter off every request that is not a
    page.

    SA-3 — the server-worker shape counts too. ``main`` becomes a generated SHIM that
    imports adapter-cloudflare's ``_worker.js``, wraps its ``fetch`` and delegates;
    ``nodejs_compat``, the ``ASSETS`` binding and any D1 binding ride along unchanged,
    so a dynamic site still reaches its database. That config carries the page
    allow-list too, for the opposite reason to the assets-only one: without it the
    asset router would serve every prerendered page itself and the shim would never be
    invoked.

    SA-2 — ``analytics_entitled`` says whether THIS site's plan buys the counter, as
    resolved at the publish seam by ``entitlements.site_analytics_entitled``. False
    deploys the pre-analytics config: no ``main``, no dataset binding, no routing
    rules, no entry on disk. The operator kill switch
    (``PAW_SITES_ANALYTICS_DISABLED``) is ANDed in one layer down and produces the
    same shape for every site, entitled or not.

    It defaults to True for the same reason ``_wrangler_jsonc``'s does, and with the
    same caveat: this is the mechanism, the gate is at the publish seam, and the
    publish seam always passes an explicitly resolved value.

    ``d1_database_id`` (DYNAMIC ripple/svelte sites) binds the site's per-tenant D1 as
    ``DB``, so a dynamic site can serve its live data WITHOUT a Workers-for-Platforms
    dispatch namespace (a paid add-on). The D1 must already exist and be migrated — the
    provision job does both before calling this.

    The project MUST already carry the engine's static output
    (``resolve_static_output_rel(project_dir, engine)`` — generator.build() emits it
    before this is called, which is what makes resolving it off disk possible).
    On a non-zero wrangler exit this raises ``Internal`` with the stderr tail so the
    failure surfaces as a clean 5xx envelope, not an opaque crash."""
    name = _worker_name(site_id)
    if not _WORKER_NAME_RE.match(name):  # defensive — _worker_name always sanitizes
        raise ValidationError(
            "sites.workers_bad_name",
            f"Computed an invalid worker name from site id {site_id!r}.",
        )
    _write_deploy_files(
        project_dir,
        name,
        engine,
        d1_database_id,
        site_id=site_id,
        analytics_entitled=analytics_entitled,
    )

    # ``--config`` is REQUIRED, not cosmetic: a dynamic project dir also holds the
    # generator's wrangler.toml (whose queue producers reference queues that do not
    # exist on this path), and wrangler must not pick it up.
    argv = [*_wrangler_argv(), "deploy", "--config", _CONFIG_FILENAME]
    logger.info(
        "sites.workers: deploying %s (engine=%s d1=%s) via %s",
        name,
        engine,
        bool(d1_database_id),
        argv,
    )
    try:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            cwd=project_dir,
            env=_cf_env(),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    except FileNotFoundError as exc:
        # wrangler / bunx not on PATH — a misconfigured deploy image.
        raise Internal(
            "sites.workers_wrangler_missing",
            "The wrangler toolchain is unavailable — a workers-mode deploy needs "
            "wrangler reachable (bunx pulls it at publish time).",
        ) from exc
    stdout_b, stderr_b = await proc.communicate()
    stdout = stdout_b.decode(errors="replace")
    stderr = stderr_b.decode(errors="replace")
    if proc.returncode != 0:
        tail = (stderr or stdout)[-800:]
        logger.error("sites.workers: wrangler deploy failed (exit %s): %s", proc.returncode, tail)
        raise Internal(
            "sites.workers_deploy_failed",
            f"wrangler deploy failed (exit {proc.returncode}): {tail}",
        )
    url = _parse_deploy_url(stdout, name=name)
    logger.info("sites.workers: deployed %s -> %s", name, url or "(url unresolved)")
    return url


__all__ = ["deploy_workers", "worker_name"]
