/**
 * Recipe engine — type contracts.
 *
 * A "source map" is the platform's representation of a site: a flat map of
 * POSIX-relative path -> file contents. Recipes are one-shot codemods that
 * compose files and deterministic edits INTO a source map and then exit. There
 * is no runtime plugin layer — after a recipe runs the result is plain,
 * customer-owned SvelteKit source.
 */

/** A site as a flat map of POSIX-relative path -> UTF-8 file contents. */
export type SourceMap = Record<string, string>;

/**
 * A named, idempotent insertion at an anchor.
 *
 * The base template ships anchor markers (e.g. `// @recipe:imports`) at every
 * shared insertion point. A splice inserts `payload` immediately before/after
 * the anchor line. Re-applying is a no-op: the engine stamps a unique sentinel
 * derived from `(recipe id, key)` and skips if that sentinel is already present.
 *
 * All splice targets are TypeScript/JavaScript comment contexts (`.ts`, the
 * `<script>` block of `.svelte`), so the sentinel is emitted as a `//` comment.
 */
export interface Splice {
	/** Source-map path of the file to edit (must already exist — fail closed). */
	file: string;
	/** Marker text that must exist in the file, e.g. `// @recipe:imports`. */
	anchor: string;
	/** Unique-within-recipe key; combined with the recipe id to form the sentinel. */
	key: string;
	/** Text to insert at the anchor. May be multi-line. */
	payload: string;
	/** Insert before or after the anchor line. Default: `after`. */
	position?: 'before' | 'after';
}

/** A file the recipe writes verbatim into the source map. */
export interface RecipeFile {
	/** Path of the payload file on disk, relative to the recipe directory. */
	from: string;
	/** Destination path in the source map. */
	to: string;
}

/** A stacked SQL migration. The engine assigns the numeric prefix. */
export interface RecipeMigration {
	/**
	 * Migration name (unique across recipes), used for the filename suffix and
	 * for idempotency detection: `migrations/NNNN_<name>.sql`.
	 */
	name: string;
	/** Path of the `.sql` payload on disk, relative to the recipe directory. */
	from: string;
}

/**
 * A recipe manifest as authored under `recipes/<id>/recipe.ts`.
 *
 * `files`/`migration` reference payload files on disk (kept as real files so
 * they can be authored/generated by CLIs and edited normally). The registry
 * loader reads those into a {@link ResolvedRecipe} before the engine runs, so
 * the engine itself stays pure and works entirely on in-memory contents.
 */
export interface Recipe {
	/** Stable identifier, e.g. `"stripe"`. Matches the directory name. */
	id: string;
	/** Human capability label, e.g. `"payments"`. */
	capability: string;
	/** Recipe ids this recipe depends on; applied first, in dependency order. */
	requires?: string[];
	/** Files written verbatim into the source map. */
	files?: RecipeFile[];
	/** Deterministic edits to existing shared files. */
	splices?: Splice[];
	/** A stacked SQL migration, or null if the recipe needs no tables. */
	migration?: RecipeMigration | null;
	/** Names of Cloudflare Worker secrets the recipe needs. VALUES NEVER LIVE IN SOURCE. */
	secrets?: string[];
	/** Runtime dependencies merged into package.json `dependencies`. */
	deps?: Record<string, string>;
	/** Dev dependencies merged into package.json `devDependencies`. */
	devDeps?: Record<string, string>;
	/** Lines added to `App.Platform['env']` at the `@recipe:env` anchor in app.d.ts. */
	envTypes?: string[];
	/** Lines added to `App.Locals` at the `@recipe:locals` anchor in app.d.ts. */
	locals?: string[];
}

/** A recipe with all on-disk payloads read into memory. The engine consumes these. */
export interface ResolvedRecipe extends Omit<Recipe, 'files' | 'migration'> {
	/** Files resolved to `{ path, contents }`. */
	files: Array<{ path: string; contents: string }>;
	/** Migration resolved to `{ name, contents }`, or null. */
	migration: { name: string; contents: string } | null;
}

/** One entry in an apply plan — a single concrete change to the source map. */
export interface PlanChange {
	recipe: string;
	kind: 'file' | 'splice' | 'migration' | 'deps' | 'env' | 'locals';
	/** Affected source-map path. */
	path: string;
	/** Short human description of the change (or "no-op (already applied)"). */
	detail: string;
	/** True when the change is a no-op because it was already applied (idempotent). */
	noop: boolean;
}

/** Result of applying recipes to a source map. */
export interface ApplyResult {
	sourceMap: SourceMap;
	plan: PlanChange[];
	/** Union of all declared secret names across applied recipes (names only). */
	secrets: string[];
	/** Applied recipe ids, in the deterministic order they were applied. */
	order: string[];
}

/** Thrown when a recipe cannot be applied. The engine writes nothing on error. */
export class RecipeError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'RecipeError';
	}
}
