# PushSubscription Beanie document — one stored browser Web Push subscription.
# Created: 2026-06-09 (feat/push-subscription-store, pocketpaw#1391) — backing
# store for the Web Push subscriptions a browser hands the backend after the
# user grants notification permission. Storage only; sending notifications
# (pywebpush dispatch + 410 pruning) lands in #1392.
# Updated: 2026-06-09 (review nits) — dropped the redundant ``created_at``
# field; ``TimestampedDocument`` already auto-sets ``createdAt`` on insert, so
# the domain/DTO surface that inherited timestamp instead of a dead column.
#
# ``endpoint`` is the natural unique key — the browser's push service mints
# one endpoint URL per subscription, and re-subscribing from the same browser
# returns the same endpoint, so a unique index makes the subscribe path
# idempotent (the service upserts on it). ``workspace`` + ``user_id`` carry
# tenancy; every read filters on ``workspace`` (ee/cloud rule §7). The
# ``keys`` sub-object holds the ECDH ``p256dh`` + ``auth`` secrets the push
# protocol needs to encrypt payloads — they are not credentials for the
# backend and are safe to store as-is.
#
# Only ``ee.cloud.push.service`` may import this module — enforced by the
# import-linter contract in ``ee/pyproject.toml``.

from __future__ import annotations

from beanie import Indexed
from pydantic import BaseModel

from pocketpaw_ee.cloud.models.base import TimestampedDocument


class PushKeys(BaseModel):
    """ECDH keys the Web Push protocol uses to encrypt the payload.

    ``p256dh`` is the client public key (base64url, uncompressed P-256
    point); ``auth`` is a base64url authentication secret. Both are
    generated by the browser's PushManager and are not backend secrets.
    """

    p256dh: str
    auth: str


class PushSubscription(TimestampedDocument):
    """One browser Web Push subscription, scoped to a workspace + user."""

    workspace: Indexed(str)  # type: ignore[valid-type]
    user_id: Indexed(str)  # type: ignore[valid-type]
    # The push-service endpoint URL. Unique across the collection so the
    # subscribe path can upsert (re-subscribing the same browser updates
    # the row instead of duplicating it).
    endpoint: Indexed(str, unique=True)  # type: ignore[valid-type]
    keys: PushKeys
    expiration_time: int | None = None  # epoch millis from PushSubscription.expirationTime
    # Captured server-side from the subscribe request's User-Agent header
    # (not trusted from the client body). Empty when the header is absent.
    user_agent: str = ""

    class Settings:
        name = "push_subscriptions"
