# ee/pocketpaw_ee/cloud/models/social_idea.py — one Growth › Social short-form
# post idea (format, hook, on-screen text, script beats, caption, hashtags and
# the one-line "why"), workspace-scoped, with a new → approved / skipped review
# status. Ideas are generated by the social ideas agent and reviewed in Blitz.
#
# Only ``ee.cloud.growth.social.service`` may import this doc class
# (import-linter "Growth" contract).

from __future__ import annotations

from beanie import Indexed
from pydantic import Field

from pocketpaw_ee.cloud.models.base import TimestampedDocument


class SocialIdea(TimestampedDocument):
    """One generated post idea in a workspace."""

    workspace: Indexed(str)  # type: ignore[valid-type]
    format: str
    hook: str
    on_screen_text: str = ""
    caption: str = ""
    why: str = ""
    script: list[str] = Field(default_factory=list)
    hashtags: list[str] = Field(default_factory=list)
    status: str = "new"

    class Settings:
        name = "growth_social_ideas"
        indexes = [
            [("workspace", 1), ("status", 1), ("createdAt", -1)],
            [("workspace", 1), ("createdAt", -1)],
        ]
