# ee/pocketpaw_ee/cloud/models/social_idea.py — one Growth › Social short-form
# post idea (format, hook, on-screen text, script beats, caption, hashtags and
# the one-line "why"), scoped to a workspace and one social profile, with a
# new → approved / skipped review status, and, once scheduled, the date and
# the /calendar event that marks it. Ideas are generated by the social
# ideas agent and reviewed in Blitz.
#
# Only ``ee.cloud.growth.social.service`` may import this doc class
# (import-linter "Growth" contract).

from __future__ import annotations

from datetime import datetime

from beanie import Indexed
from pydantic import Field

from pocketpaw_ee.cloud.models.base import TimestampedDocument


class SocialIdea(TimestampedDocument):
    """One generated post idea in a workspace."""

    workspace: Indexed(str)  # type: ignore[valid-type]
    profile: str = ""
    format: str
    hook: str
    on_screen_text: str = ""
    caption: str = ""
    why: str = ""
    script: list[str] = Field(default_factory=list)
    hashtags: list[str] = Field(default_factory=list)
    platform: str = ""
    subreddit: str = ""
    status: str = "new"
    scheduled_at: datetime | None = None
    calendar_event_id: str = ""

    class Settings:
        name = "growth_social_ideas"
        indexes = [
            [("workspace", 1), ("profile", 1), ("status", 1), ("createdAt", -1)],
            [("workspace", 1), ("profile", 1), ("createdAt", -1)],
        ]
