// Generated by @paw/sites-generator. Host onEvent (Contract clause 5).
//
// RFC 12 Amendment A1 note: on the STATIC path (`csr = false`) this never runs
// — the lead form does a native browser POST to /api/submit (see +page.svelte),
// so no client `fetch` is needed. It's kept (imported but inert) so a future
// CSR/interactive variant of the generator can reuse it unchanged. Harmless in
// the static build: under csr=false it is never bundled to the browser.
//
// Ripple's `api` action emits {type:'api', url, method, body}; this routes form
// submits to the in-app /api/submit endpoint (the edge buffer), and returns
// {ok, data|error} so Ripple's on_success/on_error chaining works.
import type { RippleEvent, RippleEventResult } from '@ripple-ui/svelte';

export async function onEvent(event: RippleEvent): Promise<RippleEventResult> {
  if (event.type !== 'api') {
    // Non-api events (toast/navigate/emit) are handled inside Ripple; ack them.
    return { ok: true };
  }
  try {
    const res = await fetch('/api/submit', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(event.body ?? {})
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return { ok: false, error: { message: 'submit failed', status: res.status, body: data } };
    }
    return { ok: true, data };
  } catch (err) {
    return { ok: false, error: { message: err instanceof Error ? err.message : 'network error' } };
  }
}
