"""Generate pocketpaw's ripple action-verb set from ripple's event-handler schema.

Created 2026-10-02 (fix/canon-cross-repo-pins, CN-8). ripple owns the verb list:
``packages/core/src/schema/event-handler.ts`` declares it as
``export const EventAction = z.enum([...])``. pocketpaw used to hand-maintain a copy
in ``pocketpaw.ripple.manifest`` and it fell behind (``animate`` was rejected as an
unknown verb). This script reads the schema at a git ref of a ripple checkout and
writes ``src/pocketpaw/ripple/_action_verbs.py``. Nothing fetches at runtime.

Updated 2026-10-02 (CN-8 review): fetches the ref's remote first; ``parse_verbs``
skips ``//`` comment lines, accepts any quoted literal, and fails unless it found
exactly one verb per comma-separated entry.

Usage:
    python scripts/vendor_ripple_verbs.py                       # ../ripple @ origin/main
    python scripts/vendor_ripple_verbs.py --ripple PATH --ref REF
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
from pathlib import Path

SOURCE_PATH = "packages/core/src/schema/event-handler.ts"
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "pocketpaw" / "ripple" / "_action_verbs.py"

_ENUM_RE = re.compile(r"export const EventAction\s*=\s*z\.enum\(\[(.*?)\]\)", re.S)


def parse_verbs(source: str) -> tuple[str, ...]:
    """The verbs in ``EventAction``'s ``z.enum([...])``, in source order."""
    match = _ENUM_RE.search(source)
    if not match:
        raise SystemExit(f"EventAction = z.enum([...]) not found in {SOURCE_PATH}")
    body = "\n".join(
        line for line in match.group(1).splitlines() if not line.strip().startswith("//")
    )
    verbs = tuple(re.findall(r"""['"]([^'"]+)['"]""", body))
    entries = [e for e in body.split(",") if e.strip()]
    if not verbs or len(verbs) != len(entries):
        raise SystemExit(
            f"EventAction in {SOURCE_PATH}: {len(verbs)} quoted verbs but "
            f"{len(entries)} entries; the enum has a shape this parser does not know"
        )
    return verbs


def verbs_sha256(verbs: tuple[str, ...] | frozenset[str]) -> str:
    return hashlib.sha256("\n".join(sorted(verbs)).encode()).hexdigest()


def read_source(ripple: Path, ref: str) -> tuple[str, str]:
    """``(commit, file text)`` for ``SOURCE_PATH`` at ``ref`` in ``ripple``."""
    git = ["git", "-C", str(ripple)]
    commit = subprocess.run(
        [*git, "rev-parse", ref], check=True, capture_output=True, text=True
    ).stdout.strip()
    text = subprocess.run(
        [*git, "show", f"{commit}:{SOURCE_PATH}"], check=True, capture_output=True, text=True
    ).stdout
    return commit, text


def render(commit: str, source: str) -> str:
    verbs = parse_verbs(source)
    lines = "".join(f'        "{v}",\n' for v in verbs)
    return (
        "# GENERATED by scripts/vendor_ripple_verbs.py. DO NOT EDIT BY HAND.\n"
        f"# Source: ripple {SOURCE_PATH} (EventAction)\n"
        f"# Commit: {commit}\n"
        "# Re-run the script to refresh; tests/test_ripple_action_verbs_vendored.py checks\n"
        "# VERBS_SHA256 always, and the source hash when a ripple checkout is beside us.\n"
        '"""Ripple event action verbs, generated from ripple\'s schema."""\n\n'
        f'SOURCE_COMMIT = "{commit}"\n'
        f'SOURCE_SHA256 = "{hashlib.sha256(source.encode()).hexdigest()}"\n'
        f'VERBS_SHA256 = "{verbs_sha256(verbs)}"\n\n'
        f"ACTION_VERBS: frozenset[str] = frozenset(\n    {{\n{lines}    }}\n)\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ripple", type=Path, default=ROOT.parent / "ripple")
    ap.add_argument("--ref", default="origin/main")
    args = ap.parse_args()
    if subprocess.run(["git", "-C", str(args.ripple), "fetch", "-q", "origin"]).returncode:
        print(f"WARN: fetch failed; using the local {args.ref}")
    commit, source = read_source(args.ripple, args.ref)
    OUT.write_text(render(commit, source), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(parse_verbs(source))} verbs @ {commit[:7]}")


if __name__ == "__main__":
    main()
