#!/usr/bin/env bash
# scripts/vendor-paw-sites-edit-bridge.sh -- re-vendor paw-sites' edit-bridge scripts.
#
# The draft preview origin serves html drafts without a build, so pocketpaw injects
# paw-sites' in-frame scripts itself (preview_origin.py):
#   ee/pocketpaw_ee/sites/edit_bridge.js       editBridgeScript(PLACEHOLDER)
#   ee/pocketpaw_ee/sites/runtime_reporter.js  runtimeReporterScript(PLACEHOLDER)
# PLACEHOLDER is the quoted "__PAW_BUILDER_ORIGIN__" that preview_origin replaces
# with the builder origin. This script regenerates both from a paw-sites commit and
# rewrites paw-sites-edit-bridge.pin.json (commit + sha256 of each file);
# tests/ee/sites/test_paw_sites_edit_bridge_vendored.py fails when they disagree.
#
# `git archive <commit> src` goes into a temp dir and bun imports edit-bridge.ts on
# its own (its imports are node: builtins and a type-only import), so no install.
#
# Usage:
#   scripts/vendor-paw-sites-edit-bridge.sh            # ../paw-sites at origin/main
#   PAW_SITES_DIR=/path/to/paw-sites PAW_SITES_REF=<ref> scripts/vendor-paw-sites-edit-bridge.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${PAW_SITES_DIR:-$HERE/../paw-sites}"
REF="${PAW_SITES_REF:-origin/main}"
SITES="$HERE/ee/pocketpaw_ee/sites"
PIN="$SITES/paw-sites-edit-bridge.pin.json"

[ -e "$SRC/.git" ] || { echo "ERROR: paw-sites checkout not found at '$SRC'" >&2; exit 1; }
git -C "$SRC" fetch -q origin || echo "[vendor-paw-sites-edit-bridge] WARN: fetch failed; using the local $REF" >&2
COMMIT="$(git -C "$SRC" rev-parse "$REF")"
SHORT="${COMMIT:0:7}"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
git -C "$SRC" archive "$COMMIT" src | tar -x -C "$TMP"
cat > "$TMP/print.ts" <<'TS'
import { editBridgeScript, runtimeReporterScript } from './src/edit-bridge.ts';
const which = process.argv[2];
const fn = which === 'bridge' ? editBridgeScript : runtimeReporterScript;
process.stdout.write(fn('__PAW_BUILDER_ORIGIN__') + '\n');
TS

emit() { # $1 = bridge|reporter, $2 = dest file, $3 = what the file is for
  {
    echo "// ee/pocketpaw_ee/sites/$(basename "$2") --"
    echo "// $3"
    echo "//"
    echo "// Generated by scripts/vendor-paw-sites-edit-bridge.sh from paw-sites $SHORT"
    echo "// (src/edit-bridge.ts). Do not hand-edit. The quoted \"__PAW_BUILDER_ORIGIN__\""
    echo "// placeholder is replaced with the builder origin by preview_origin.py."
    echo
    ( cd "$TMP" && bun print.ts "$1" )
  } > "$2.tmp"
  mv "$2.tmp" "$2"
}
emit bridge "$SITES/edit_bridge.js" \
  "the paw-sites edit-bridge, injected into html drafts served with ?paw_edit=1."
emit reporter "$SITES/runtime_reporter.js" \
  "the paw-sites runtime-error reporter, put at the top of every html draft page."

python3 - "$PIN" "$COMMIT" "$SITES/edit_bridge.js" "$SITES/runtime_reporter.js" <<'PY'
import hashlib, json, os, sys
pin, commit, *files = sys.argv[1:]
data = {
    "source_repo": "qbtrix/paw-sites",
    "source_path": "src/edit-bridge.ts (editBridgeScript / runtimeReporterScript)",
    "source_commit": commit,
    "sha256": {
        os.path.basename(f): hashlib.sha256(open(f, "rb").read().replace(b"\r\n", b"\n")).hexdigest()
        for f in files
    },
}
open(pin, "w", encoding="utf-8").write(json.dumps(data, indent=2) + "\n")
print(f"[vendor-paw-sites-edit-bridge] {commit[:7]} {data['sha256']}")
PY
