# Code Mode stub generator — emits a ``paw_tools.py`` module the agent's
# script imports to call read-safe internal tools.
# Created: 2026-06-16 (feat/code-mode-ptc) — Programmatic Tool Calling v1.
#
# For each READ-SAFE registered tool (filtered through code_mode.safety) this
# emits one typed stub function whose body is a single ``_call("tool_name",
# {...})`` over the RPC bridge. Intermediate results stay inside the sandbox;
# only what the script prints to stdout returns to the LLM.
#
# The generated module is DATA the runner writes to a throwaway dir — it is
# never imported into the host process. ``_call`` talks to a Unix-domain-socket
# bridge whose path is read from the ``PAW_CODE_MODE_SOCKET`` env var the runner
# sets. The bridge re-validates the read-safe allowlist on every call, so the
# stub list is a convenience, never the security boundary.

from __future__ import annotations

import keyword
from typing import Any

from pocketpaw.tools.code_mode.safety import is_read_safe_tool

# Header prepended to the generated module — defines the ``_call`` transport.
# Kept dependency-free (stdlib only) so the sandbox child needs nothing beyond
# the interpreter. The socket path arrives via env (never hard-coded) so two
# concurrent runs never collide.
_RUNTIME_HEADER = '''# AUTO-GENERATED by PocketPaw Code Mode — do not edit.
# One typed stub per read-safe internal tool. Each stub round-trips through the
# RPC bridge, which RE-VALIDATES the read-safe allowlist on every call.
"""PocketPaw read-safe tool stubs for code-mode scripts."""

import json as _json
import os as _os
import socket as _socket

_SOCKET_PATH = _os.environ.get("PAW_CODE_MODE_SOCKET", "")
_MAX_FRAME = 8 * 1024 * 1024  # 8 MiB ceiling on a single RPC frame.


def _call(name, args):
    """Send ``(name, args)`` to the bridge and return its string result.

    Newline-delimited JSON over a Unix domain socket. The bridge dispatches
    through the real ToolRegistry chokepoint (policy + audit + capping) and
    re-validates that ``name`` is read-safe — a write/gated tool is rejected
    here even if a hand-edited script tries to call it directly.
    """
    if not _SOCKET_PATH:
        raise RuntimeError("code-mode bridge socket not configured")
    payload = _json.dumps({"name": name, "args": args or {}}).encode("utf-8")
    if len(payload) > _MAX_FRAME:
        raise RuntimeError("code-mode request too large")
    with _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM) as sock:
        sock.connect(_SOCKET_PATH)
        sock.sendall(payload + b"\\n")
        sock.shutdown(_socket.SHUT_WR)
        chunks = []
        size = 0
        while True:
            chunk = sock.recv(65536)
            if not chunk:
                break
            size += len(chunk)
            if size > _MAX_FRAME:
                raise RuntimeError("code-mode response too large")
            chunks.append(chunk)
    raw = b"".join(chunks).decode("utf-8", "replace").strip()
    if not raw:
        return ""
    reply = _json.loads(raw)
    if not reply.get("ok", False):
        raise RuntimeError(reply.get("error", "code-mode tool call failed"))
    return reply.get("result", "")
'''


def _safe_param_name(raw: str) -> str:
    """Coerce a JSON-schema property name into a valid Python identifier.

    Tool param names are author-controlled JSON keys; sanitize so a weird key
    can't produce a syntactically broken stub. A reserved word gets a trailing
    underscore; a non-identifier is dropped (the caller passes it positionally
    is impossible, so we simply skip emitting a named param for it and the stub
    still works via **kwargs-free explicit dict assembly below)."""
    candidate = raw if raw.isidentifier() else ""
    if not candidate:
        return ""
    if keyword.iskeyword(candidate):
        return candidate + "_"
    return candidate


def _stub_for(tool: Any) -> str:
    """Render one stub function for ``tool``.

    The stub takes the tool's declared params as ``**kwargs`` (kept simple and
    robust — JSON-schema params vary widely and the bridge validates required
    params anyway), drops ``None`` values, and forwards the rest as the args
    dict. A short docstring carries the tool's description for the LLM author.
    """
    name = tool.name
    try:
        schema = tool.definition.parameters or {}
    except Exception:  # noqa: BLE001 — a broken definition shouldn't kill stubgen
        schema = {}
    props = schema.get("properties", {}) if isinstance(schema, dict) else {}
    required = schema.get("required", []) if isinstance(schema, dict) else []

    description = (getattr(tool, "description", "") or "").strip().replace('"""', "'''")

    # Build a readable signature: required params first (no default), optional
    # params with ``=None``. Params whose names aren't valid identifiers are
    # still accepted via ``**extra`` so nothing is silently lost.
    req_params: list[str] = []
    opt_params: list[str] = []
    arg_assigns: list[str] = []
    for pname in props:
        safe = _safe_param_name(pname)
        if not safe:
            continue
        if pname in required:
            req_params.append(safe)
        else:
            opt_params.append(f"{safe}=None")
        # Map the python arg name back to the original JSON key.
        arg_assigns.append(f"    if {safe} is not None:\n        _args[{pname!r}] = {safe}")

    sig_parts = req_params + opt_params + ["**extra"]
    signature = ", ".join(sig_parts)

    body_lines = [f"def {_safe_func_name(name)}({signature}):"]
    if description:
        body_lines.append(f'    """{description}"""')
    body_lines.append("    _args = {}")
    body_lines.extend(arg_assigns)
    body_lines.append("    if extra:\n        _args.update(extra)")
    body_lines.append(f"    return _call({name!r}, _args)")
    return "\n".join(body_lines)


def _safe_func_name(tool_name: str) -> str:
    """Tool names are already snake_case identifiers in practice; guard anyway."""
    if tool_name.isidentifier() and not keyword.iskeyword(tool_name):
        return tool_name
    cleaned = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in tool_name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "tool_" + cleaned
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def read_safe_tools(registry: Any) -> list[Any]:
    """Return the registry's tools that pass the read-safe gate, name-sorted.

    Uses :func:`is_read_safe_tool` — the SAME predicate the bridge re-validates
    against, so the stub surface and the bridge allowlist can never drift.
    """
    tools = []
    for name in registry.tool_names:
        tool = registry.get(name)
        if tool is not None and is_read_safe_tool(tool):
            tools.append(tool)
    return sorted(tools, key=lambda t: t.name)


def generate_stub_module(registry: Any) -> str:
    """Generate the full ``paw_tools.py`` source for a registry.

    Filters to read-safe tools, emits ``_call`` + one stub each, and a
    ``__all__`` listing the callable tool names. Returns the module source as a
    string the runner writes to the sandbox dir.
    """
    tools = read_safe_tools(registry)
    parts = [_RUNTIME_HEADER, ""]
    names = []
    for tool in tools:
        parts.append(_stub_for(tool))
        parts.append("")
        names.append(_safe_func_name(tool.name))
    all_list = ", ".join(repr(n) for n in names)
    parts.append(f"__all__ = [{all_list}]")
    parts.append("")
    return "\n".join(parts)
