# tests/ee/sites/test_legacy_build_shell.py
# Created 2026-09-24 (fix/sites-legacy-build-shell-migration, PP-4). Covers the
# legacy build-shell migration end to end:
#   1. the pure classifier matrix: every reserved file x SAFE_DROP / CONVERTIBLE /
#      NEEDS_REVIEW, plus case and backslash spellings;
#   2. the runner against a real (mongomock) pocket: dry run writes nothing, apply
#      drops/converts through the pockets service and records a draft version, a
#      second run is a no-op, a mixed pocket keeps its review files, paging resumes;
#   3. the runtime safety net: the generator's structured reserved_path refusal and
#      the preflight both surface a 422 that names the file.
from __future__ import annotations

import json

import pytest
from pocketpaw_ee.cloud._core.errors import CloudError
from pocketpaw_ee.cloud.pockets import service as pockets_service
from pocketpaw_ee.sites import generator_client as gc
from pocketpaw_ee.sites import service as sites_service
from pocketpaw_ee.sites.dependency_resolver import Rejection, ResolvedPackage, ResolveResult
from pocketpaw_ee.sites.legacy_build_shell import (
    MIGRATION_AUTHOR,
    Classification,
    classify_source,
    generator_owned_keys,
    run_migration,
)

SAFE = Classification.SAFE_DROP
CONV = Classification.CONVERTIBLE
REVIEW = Classification.NEEDS_REVIEW

_PAGE = {"src/routes/+page.svelte": "<h1>Hi</h1>", "src/routes/+layout.svelte": "<slot/>"}

SVELTE_VITE = (
    '// Generated by @paw/sites-generator — svelte track (engine="svelte").\n'
    "import { sveltekit } from '@sveltejs/kit/vite';\n"
    "import { defineConfig } from 'vite';\n\n"
    "export default defineConfig({ plugins: [sveltekit()] });\n"
)
REACT_VITE = (
    "import { defineConfig } from 'vite';\n"
    "import react from '@vitejs/plugin-react';\n"
    "export default defineConfig({ plugins: [react()] });\n"
)
STATIC_SVELTE_CONFIG = """// Generated by @paw/sites-generator — static svelte track (SL-1).
import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

export default {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter(),
    prerender: { handleMissingId: 'warn', handleHttpError: 'warn' }
  },
  compilerOptions: { experimental: { async: true } }
};
"""
SVELTE_PKG = {
    "name": "paw-site-x",
    "private": True,
    "type": "module",
    "scripts": {"dev": "vite dev", "build": "vite build", "preview": "vite preview"},
    "devDependencies": {
        "@cloudflare/workers-types": "^4.20240909.0",
        "@sveltejs/adapter-static": "^3.0.10",
        "@sveltejs/kit": "^2.0.0",
        "@sveltejs/vite-plugin-svelte": "^6.0.0",
        "svelte": "^5.0.0",
        "vite": "^6.0.0",
    },
}


def _one(engine, key, text, *, kcb=True, dynamic=False, extra=None):
    source = {**_PAGE, **(extra or {}), key: text}
    findings = classify_source(engine, source, keeps_client_bundle=kcb, dynamic=dynamic)
    assert [f.key for f in findings] == [key], findings
    return findings[0]


def _pkg(**over):
    pkg = json.loads(json.dumps(SVELTE_PKG))
    for k, v in over.items():
        if v is None:
            pkg.pop(k, None)
        else:
            pkg[k] = v
    return json.dumps(pkg)


# ── 1. classifier ────────────────────────────────────────────────────────────


def test_clean_source_has_no_findings():
    assert classify_source("svelte", _PAGE, keeps_client_bundle=True) == []


def test_canonical_manifest_is_not_a_finding():
    source = {**_PAGE, "paw.dependencies.json": '{"schema":1,"packages":{}}'}
    assert generator_owned_keys("svelte", source) == []


@pytest.mark.parametrize(
    "key", ["package.json", "Package.JSON", "./package.json", "src\\..\\package.json"]
)
def test_stock_package_json_is_safe_in_any_spelling(key):
    assert _one("svelte", key, _pkg()).classification is SAFE


def test_package_json_with_author_packages_is_convertible():
    f = _one("svelte", "package.json", _pkg(dependencies={"motion": "^12.40.0", "gsap": "3.15.0"}))
    assert f.classification is CONV
    assert dict(f.requests) == {"motion": "^12.40.0", "gsap": "3.15.0"}


def test_package_json_author_packages_without_client_bundle_needs_review():
    f = _one("svelte", "package.json", _pkg(dependencies={"motion": "^12.40.0"}), kcb=False)
    assert f.classification is REVIEW


@pytest.mark.parametrize(
    "pkg",
    [
        _pkg(overrides={"x": "1.0.0"}),
        _pkg(scripts={"build": "vite build && curl evil"}),
        _pkg(devDependencies={"svelte": "^4.0.0"}),
        _pkg(dependencies={"tailwindcss": "^4.2.2"}),
        _pkg(dependencies={"x": "git+https://github.com/a/b"}),
        "not json",
        "[]",
    ],
)
def test_package_json_review_cases(pkg):
    assert _one("svelte", "package.json", pkg).classification is REVIEW


def test_react_package_json_stock_is_safe():
    pkg = json.dumps(
        {
            "dependencies": {"react": "^19.0.0", "react-dom": "^19.0.0"},
            "devDependencies": {"@vitejs/plugin-react": "^4.3.4", "vite": "^6.0.0"},
        }
    )
    assert _one("react", "package.json", pkg).classification is SAFE


@pytest.mark.parametrize("ext", ["ts", "js", "mjs", "mts", "cjs", "cts"])
def test_stock_vite_config_is_safe_in_every_spelling(ext):
    assert _one("svelte", f"vite.config.{ext}", SVELTE_VITE).classification is SAFE
    assert _one("react", f"VITE.config.{ext}", REACT_VITE).classification is SAFE


def test_vite_config_without_define_config_is_safe():
    text = (
        'import { sveltekit } from "@sveltejs/kit/vite"\nexport default { plugins: [sveltekit(),] }'
    )
    assert _one("svelte", "vite.config.js", text).classification is SAFE


def test_vite_config_with_extra_plugin_needs_review():
    text = SVELTE_VITE.replace("sveltekit()]", "sveltekit(), tailwindcss()]")
    assert _one("svelte", "vite.config.ts", text).classification is REVIEW


def test_generator_svelte_config_is_safe_and_an_older_subset_too():
    assert _one("svelte", "svelte.config.js", STATIC_SVELTE_CONFIG).classification is SAFE
    minimal = (
        "import adapter from '@sveltejs/adapter-static';\n"
        "export default { kit: { adapter: adapter() } };"
    )
    assert _one("svelte", "svelte.config.js", minimal).classification is SAFE


def test_svelte_config_with_alias_needs_review():
    text = STATIC_SVELTE_CONFIG.replace(
        "adapter: adapter(),", "adapter: adapter(), alias: { x: 'y' },"
    )
    assert _one("svelte", "svelte.config.js", text).classification is REVIEW


@pytest.mark.parametrize(
    ("text", "kcb", "expected"),
    [
        ("export const prerender = true;", True, SAFE),
        ("export const prerender = true;\nexport const csr = false;", False, SAFE),
        ("// flags\nexport const prerender = true\nexport const csr = true\n", True, SAFE),
        ("export const prerender = true;\nexport const ssr = true;", True, SAFE),
        ("", True, SAFE),
        ("export const prerender = true;\nexport const csr = false;", True, REVIEW),
        ("export const prerender = true;", False, REVIEW),
        ("export const prerender = false;", True, REVIEW),
        ("export const prerender = true;\nexport function load() { return {a: 1} }", True, REVIEW),
        ("import x from '$lib/x';\nexport const prerender = true;", True, REVIEW),
        ("export const trailingSlash = 'always';", True, REVIEW),
    ],
)
@pytest.mark.parametrize("key", ["src/routes/+layout.ts", "src\\routes\\+LAYOUT.js"])
def test_layout_matrix(key, text, kcb, expected):
    assert _one("svelte", key, text, kcb=kcb).classification is expected


@pytest.mark.parametrize("key", ["bun.lock", "bun.lockb", "package-lock.json", "Bun.Lock"])
def test_lockfiles_are_safe(key):
    assert _one("svelte", key, "{}").classification is SAFE
    assert _one("react", key, "{}").classification is SAFE


@pytest.mark.parametrize("key", ["bunfig.toml", ".npmrc"])
def test_install_config(key):
    assert _one("svelte", key, "# nothing\n\n").classification is SAFE
    assert _one("react", key, "registry=https://evil.example\n").classification is REVIEW


def test_manifest_variant_is_convertible_and_empty_one_safe():
    text = '{"schema":1,"packages":{"three":{"version":"0.170.0"}}}'
    f = _one("svelte", "PAW.dependencies.json", text)
    assert f.classification is CONV
    assert f.requests == (("three", "0.170.0"),)
    assert _one("html", ".\\paw.dependencies.json", '{"packages":{}}').classification is SAFE


def test_manifest_variant_next_to_canonical_needs_review():
    f = _one(
        "svelte",
        "Paw.Dependencies.json",
        '{"packages":{}}',
        extra={"paw.dependencies.json": '{"packages":{}}'},
    )
    assert f.classification is REVIEW


def test_pre_ps1_namespace_is_review():
    assert _one("svelte", "src/lib/paw/data.ts", "x").classification is REVIEW
    assert _one("react", "index.html", "<html>").classification is REVIEW


def test_non_text_value_is_review():
    assert _one("svelte", "package.json", {"b64": "x"}).classification is REVIEW


# ── 2. runner ────────────────────────────────────────────────────────────────


def _fake_resolver(reject: set[str] | None = None):
    calls: list[list[str]] = []

    async def resolve(requests, engine, *, already_declared=()):  # noqa: ARG001
        calls.append([r.name for r in requests])
        out = ResolveResult()
        for r in requests:
            if reject and r.name in reject:
                out.rejected.append(Rejection(r.name, "advisory", "blocked"))
            else:
                out.packages[r.name] = ResolvedPackage(r.name, "12.40.1")
        return out

    resolve.calls = calls  # type: ignore[attr-defined]
    return resolve


async def _make_pocket(source, engine="svelte", kcb=None) -> str:
    _view, pocket_id, err = await pockets_service.agent_create(
        workspace_id="w1",
        owner_id="u1",
        name="Legacy",
        type_="site",
        pattern="landing",
        ripple_spec=None,
        engine=engine,
        source=dict(source),
        trusted=True,
        keeps_client_bundle=kcb,
    )
    assert err is None, err
    return pocket_id


async def _source(pocket_id):
    return (await pockets_service.get(pocket_id, "u1"))["source"]


async def _versions(pocket_id):
    from pocketpaw_ee.versions import service as versions

    return await versions.list_versions(scope_type="pocket", scope_id=pocket_id)


LEGACY = {
    **_PAGE,
    "package.json": _pkg(dependencies={"motion": "^12.40.0"}),
    "vite.config.ts": SVELTE_VITE,
    "src/routes/+layout.ts": "export const prerender = true;",
    "bun.lock": "{}",
}


def _run(**kw):
    kw.setdefault("_keeps_client_bundle", lambda p: p.get("keepsClientBundle") is not False)
    return run_migration(**kw)


@pytest.mark.asyncio
async def test_dry_run_reports_and_writes_nothing(beanie_test_db):
    pocket_id = await _make_pocket(LEGACY)
    before = await _versions(pocket_id)

    report = await _run(_resolve=_fake_resolver())

    assert report["mode"] == "dry_run"
    assert report["affected_pockets"] == 1 and report["migrated_pockets"] == 0
    [entry] = report["pockets"]
    classes = {row["file"]: row["class"] for row in entry["files"]}
    assert classes == {
        "bun.lock": "safe_drop",
        "package.json": "convertible",
        "src/routes/+layout.ts": "safe_drop",
        "vite.config.ts": "safe_drop",
    }
    assert await _source(pocket_id) == LEGACY
    assert len(await _versions(pocket_id)) == len(before)


@pytest.mark.asyncio
async def test_apply_migrates_records_a_draft_and_is_idempotent(beanie_test_db):
    pocket_id = await _make_pocket(LEGACY)
    before = len(await _versions(pocket_id))

    report = await _run(apply=True, _resolve=_fake_resolver())

    assert report["migrated_pockets"] == 1 and not report["errors"]
    source = await _source(pocket_id)
    assert set(source) == {*_PAGE, "paw.dependencies.json"}
    assert json.loads(source["paw.dependencies.json"])["packages"] == {
        "motion": {"version": "12.40.1"}
    }
    versions = await _versions(pocket_id)
    assert len(versions) == before + 1
    assert versions[0].author == MIGRATION_AUTHOR
    assert versions[0].status == "draft"
    assert versions[0].content == source

    again = await _run(apply=True, _resolve=_fake_resolver())
    assert again["affected_pockets"] == 0 and again["migrated_pockets"] == 0
    assert len(await _versions(pocket_id)) == before + 1


@pytest.mark.asyncio
async def test_mixed_pocket_applies_safe_files_and_keeps_review_ones(beanie_test_db):
    source = {
        **_PAGE,
        "vite.config.ts": SVELTE_VITE,
        "src/routes/+layout.ts": "export const load = () => ({ a: 1 });",
        "package.json": _pkg(dependencies={"left-pad": "^1.0.0"}),
    }
    pocket_id = await _make_pocket(source)

    report = await _run(apply=True, _resolve=_fake_resolver(reject={"left-pad"}))

    after = await _source(pocket_id)
    assert "vite.config.ts" not in after
    assert after["src/routes/+layout.ts"] == source["src/routes/+layout.ts"]
    assert after["package.json"] == source["package.json"]
    assert "paw.dependencies.json" not in after
    rows = {r["file"]: r for r in report["pockets"][0]["files"]}
    assert rows["package.json"]["class"] == "needs_review"
    assert rows["package.json"]["rejected"][0]["name"] == "left-pad"
    assert report["summary"] == {"safe_drop": 1, "convertible": 0, "needs_review": 2}


@pytest.mark.asyncio
async def test_existing_manifest_entries_win_and_merge(beanie_test_db):
    manifest = '{"schema":1,"packages":{"motion":{"version":"12.0.0"}}}'
    source = {
        **_PAGE,
        "paw.dependencies.json": manifest,
        "package.json": _pkg(dependencies={"motion": "^12.40.0", "gsap": "^3.15.0"}),
    }
    pocket_id = await _make_pocket(source)
    resolver = _fake_resolver()

    await _run(apply=True, _resolve=resolver)

    assert resolver.calls == [["gsap"]]
    packages = json.loads((await _source(pocket_id))["paw.dependencies.json"])["packages"]
    assert packages == {"gsap": {"version": "12.40.1"}, "motion": {"version": "12.0.0"}}


@pytest.mark.asyncio
async def test_apply_refuses_a_file_edited_after_classification(beanie_test_db):
    pocket_id = await _make_pocket({**_PAGE, "bun.lock": "{}"})
    with pytest.raises(CloudError) as info:
        await pockets_service.migrate_legacy_build_shell(
            pocket_id, workspace_id="w1", remove={"bun.lock": "OLD"}, manifest=None, author="x"
        )
    assert info.value.status_code == 409
    assert "bun.lock" in await _source(pocket_id)


@pytest.mark.asyncio
async def test_runner_pages_and_resumes(beanie_test_db):
    ids = [await _make_pocket({**_PAGE, "bun.lock": "{}"}) for _ in range(3)]
    await _make_pocket({**_PAGE, "bun.lock": "{}"}, engine="html")  # html: not reserved

    first = await _run(limit=2, batch_size=1, _resolve=_fake_resolver())
    assert first["scanned"] == 2 and first["last_pocket_id"] == ids[1]
    rest = await _run(after=first["last_pocket_id"], _resolve=_fake_resolver())
    assert [p["pocket_id"] for p in rest["pockets"]] == [ids[2]]
    assert rest["scanned"] == 2  # the html pocket is scanned but has no findings


@pytest.mark.asyncio
async def test_no_resolve_dry_run_reports_requests(beanie_test_db):
    await _make_pocket(LEGACY)
    report = await _run(resolve_packages=False, _resolve=None)
    rows = {r["file"]: r for r in report["pockets"][0]["files"]}
    assert rows["package.json"]["requests"] == {"motion": "^12.40.0"}
    with pytest.raises(ValueError):
        await _run(apply=True, resolve_packages=False)


# ── 3. runtime safety net ────────────────────────────────────────────────────


def test_parse_generator_refusal_reads_the_reserved_path():
    line = json.dumps(
        {
            "error": 'source map may not write the generator-owned path "src/routes/+layout.ts" '
            "(reserved: ...)",
            "code": "reserved_path",
        }
    )
    refusal = gc.parse_generator_refusal("some log\n" + line + "\n")
    assert refusal is not None and refusal.code == "reserved_path"
    assert refusal.path == "src/routes/+layout.ts"
    assert isinstance(refusal, RuntimeError)
    assert gc.parse_generator_refusal('{"error":"boom","code":"internal_error"}') is None
    assert gc.parse_generator_refusal("not json") is None


@pytest.mark.asyncio
async def test_build_or_cloud_error_names_the_reserved_file():
    class _Refusing:
        async def build(self, **_kw):
            raise gc.GeneratorRefused("reserved_path", "x", "package.json")

    with pytest.raises(CloudError) as info:
        await sites_service._build_or_cloud_error(_Refusing(), map_smoke_gate=False)
    assert info.value.status_code == 422
    assert info.value.code == "sites.generator_owned_file"
    assert "`package.json`" in info.value.message


@pytest.mark.asyncio
async def test_other_refusals_keep_the_generic_envelope():
    class _Refusing:
        async def build(self, **_kw):
            raise gc.GeneratorRefused("dependency_policy", "x")

    with pytest.raises(CloudError) as info:
        await sites_service._build_or_cloud_error(_Refusing())
    assert info.value.code == "sites.generator_failed"


@pytest.mark.asyncio
async def test_preview_of_an_unmigrated_pocket_names_the_file(beanie_test_db):
    pocket_id = await _make_pocket({**_PAGE, "vite.config.ts": SVELTE_VITE})

    class _Store:
        def read(self, *_a):
            return None

    class _Pool:
        async def enqueue_job(self, *a, **kw):  # pragma: no cover - must not be reached
            raise AssertionError("queued a build that cannot succeed")

    with pytest.raises(CloudError) as info:
        await sites_service.get_native_artifact(
            workspace_id="w1",
            user_id="u1",
            pocket_id=pocket_id,
            builder_origin="https://dash.paw.example",
            _store=_Store(),
            _pool=_Pool(),
        )
    assert info.value.code == "sites.generator_owned_file"
    assert "`vite.config.ts`" in info.value.message


@pytest.mark.asyncio
async def test_publish_of_an_unmigrated_pocket_names_the_file_before_building():
    class _Gen:
        async def build(self, **_kw):  # pragma: no cover - must not be reached
            raise AssertionError("built a pocket the generator will refuse")

    with pytest.raises(CloudError) as info:
        await sites_service._deploy_site_doc(
            workspace_id="w1",
            user_id="u1",
            pocket_id="p1",
            site_id="507f1f77bcf86cd799439011",
            signed_key="k",
            site_name="s",
            ripple_spec=None,
            theme={},
            engine="svelte",
            source={**_PAGE, "Package.json": "{}"},
            generator=_Gen(),
        )
    assert info.value.code == "sites.generator_owned_file"
    assert "`Package.json`" in info.value.message
